/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * cadastroCliente.java
 *
 * Created on 17/08/2011, 11:06:17
 */
package br.com.mectex.cadastros.cliente;

import br.com.mectex.conectionDB.conexão;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author denis
 */
public class cadastroCliente extends javax.swing.JDialog {

    Validação objtoVerf = new  Validação();
     Date data = new Date();
     conexão ob = new conexão();
    Connection con = (Connection) new conexão().getConnection();
    DadosCliente obDados = new DadosCliente();
   
       
    private String foto;
    private  String sexualidade = "";
    private int navega = 0;
    private int edit = 0;
    private int novo=0;
    private int barra = 0;
     private  ResultSet rs;
     private PreparedStatement stm;
    
    public cadastroCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        travarCampos();    
        
        try {
            stm = (PreparedStatement) con.prepareStatement("select * from cadastro_cliente");
            stm.executeQuery();
            rs = stm.executeQuery();
            rs.first();
            mostrar(rs);

            navega = 1;
           
                     
                    
        } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null,"Erro ao selecionar tabela de clientes","ERRO",JOptionPane.ERROR_MESSAGE);   
        
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        BuscaNome = new javax.swing.JTextField();
        buscaCPF = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        masculino = new javax.swing.JRadioButton();
        feminino = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        fotux = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        codigo1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        bairro = new javax.swing.JTextField();
        cep = new javax.swing.JFormattedTextField();
        numero = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        cidade = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        telefone = new javax.swing.JFormattedTextField();
        jLabel30 = new javax.swing.JLabel();
        celular = new javax.swing.JFormattedTextField();
        jLabel31 = new javax.swing.JLabel();
        rg = new javax.swing.JFormattedTextField();
        jLabel32 = new javax.swing.JLabel();
        nascimento = new javax.swing.JFormattedTextField();
        jLabel34 = new javax.swing.JLabel();
        registro = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        uf = new javax.swing.JComboBox();
        endereco = new javax.swing.JTextField();
        cpf = new javax.swing.JFormattedTextField();
        jLabel38 = new javax.swing.JLabel();
        Fotu = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        Ultimo1 = new javax.swing.JButton();
        Proximo1 = new javax.swing.JButton();
        Anterior1 = new javax.swing.JButton();
        Primeiro1 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        email1 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        site = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        residencia = new javax.swing.JComboBox();
        estadocivil1 = new javax.swing.JComboBox();
        jLabel43 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        extra = new javax.swing.JTextArea();
        Confirmar = new javax.swing.JButton();
        editar = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        excluir = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de cliente");
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Procure o seu cliente.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(255, 51, 0))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel23.setForeground(new java.awt.Color(102, 102, 102));
        jLabel23.setText("RG");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 30, 20));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel24.setForeground(new java.awt.Color(102, 102, 102));
        jLabel24.setText("Nome");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 40, 20));

        BuscaNome.setFont(new java.awt.Font("Tahoma", 1, 11));
        BuscaNome.setToolTipText("Digite o nome do cliente e aperte 'Enter' para efetuar a busca");
        BuscaNome.setMaximumSize(new java.awt.Dimension(20, 20));
        BuscaNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscaNomeActionPerformed(evt);
            }
        });
        jPanel3.add(BuscaNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 200, -1));

        buscaCPF.setFont(new java.awt.Font("Tahoma", 1, 11));
        buscaCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaCPFActionPerformed(evt);
            }
        });
        jPanel3.add(buscaCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 110, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 430, 60));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sexo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(255, 51, 0))); // NOI18N
        jPanel4.setToolTipText("Escolha o Sexo do cliente");
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        masculino.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(masculino);
        masculino.setFont(new java.awt.Font("Tahoma", 1, 12));
        masculino.setText("Masculino");
        masculino.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                masculinoItemStateChanged(evt);
            }
        });
        masculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masculinoActionPerformed(evt);
            }
        });
        jPanel4.add(masculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        feminino.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(feminino);
        feminino.setFont(new java.awt.Font("Tahoma", 1, 12));
        feminino.setText("Feminino");
        feminino.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                femininoItemStateChanged(evt);
            }
        });
        jPanel4.add(feminino, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 190, 60));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Digite os dados do cliente.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(255, 51, 0))); // NOI18N
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        fotux.setToolTipText("Foto do Cliente *Opcional");
        fotux.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fotux, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fotux, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 130, 150));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Celular");
        jPanel7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 50, 20));

        nome.setFont(new java.awt.Font("Tahoma", 1, 11));
        nome.setToolTipText("Digite o nome completo do cliente ");
        nome.setNextFocusableComponent(endereco);
        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });
        jPanel7.add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 210, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("Nome");
        jPanel7.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 40, 20));

        codigo1.setEditable(false);
        codigo1.setFont(new java.awt.Font("Tahoma", 1, 11));
        codigo1.setToolTipText("Codigo do Cliente");
        codigo1.setFocusable(false);
        codigo1.setRequestFocusEnabled(false);
        jPanel7.add(codigo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 110, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setText("Endereço");
        jPanel7.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 20));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setText("Codigo");
        jPanel7.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 50, 20));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel26.setForeground(new java.awt.Color(102, 102, 102));
        jLabel26.setText("UF:");
        jPanel7.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 20, 20));

        bairro.setFont(new java.awt.Font("Tahoma", 1, 11));
        jPanel7.add(bairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 100, -1));

        try {
            cep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cep.setToolTipText("");
        cep.setFont(new java.awt.Font("Tahoma", 1, 11));
        cep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cepActionPerformed(evt);
            }
        });
        cep.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cepFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cepFocusLost(evt);
            }
        });
        jPanel7.add(cep, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 110, -1));

        numero.setFont(new java.awt.Font("Tahoma", 1, 11));
        numero.setToolTipText("Numero da Residencia");
        jPanel7.add(numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 50, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel28.setForeground(new java.awt.Color(102, 102, 102));
        jLabel28.setText("CEP");
        jPanel7.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 30, 20));

        cidade.setFont(new java.awt.Font("Tahoma", 1, 11));
        cidade.setToolTipText("Cidade onde o cliente mora");
        jPanel7.add(cidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 110, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel29.setForeground(new java.awt.Color(102, 102, 102));
        jLabel29.setText("Bairro");
        jPanel7.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 50, 20));

        try {
            telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(###)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        telefone.setFont(new java.awt.Font("Tahoma", 1, 11));
        telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefoneActionPerformed(evt);
            }
        });
        jPanel7.add(telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 100, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel30.setForeground(new java.awt.Color(102, 102, 102));
        jLabel30.setText("Cidade");
        jPanel7.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 50, 20));

        try {
            celular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(###) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        celular.setFont(new java.awt.Font("Tahoma", 1, 11));
        jPanel7.add(celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 110, -1));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel31.setForeground(new java.awt.Color(102, 102, 102));
        jLabel31.setText("Telefone");
        jPanel7.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 60, 20));

        try {
            rg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        rg.setFont(new java.awt.Font("Tahoma", 1, 11));
        jPanel7.add(rg, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 100, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel32.setForeground(new java.awt.Color(102, 102, 102));
        jLabel32.setText("RG");
        jPanel7.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 20, 20));

        try {
            nascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        nascimento.setFont(new java.awt.Font("Tahoma", 1, 11));
        nascimento.setNextFocusableComponent(estadocivil1);
        jPanel7.add(nascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 110, -1));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel34.setForeground(new java.awt.Color(102, 102, 102));
        jLabel34.setText("Registro");
        jPanel7.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 60, 20));

        registro.setFont(new java.awt.Font("Tahoma", 1, 11));
        registro.setEnabled(false);
        registro.setRequestFocusEnabled(false);
        jPanel7.add(registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 100, -1));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel35.setForeground(new java.awt.Color(102, 102, 102));
        jLabel35.setText("Numero");
        jPanel7.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 50, 20));

        uf.setFont(new java.awt.Font("Tahoma", 1, 11));
        uf.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SP", "RJ", "MG", "PA", "PB", "PR", "TO", "AM", "BA", "SC" }));
        uf.setToolTipText("Estado ");
        jPanel7.add(uf, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 50, -1));

        endereco.setFont(new java.awt.Font("Tahoma", 1, 11));
        endereco.setToolTipText("Digite o endereço do cliente ");
        jPanel7.add(endereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 210, 20));

        try {
            cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cpf.setToolTipText("CPF do Cliente");
        cpf.setFont(new java.awt.Font("Tahoma", 1, 11));
        cpf.setNextFocusableComponent(nascimento);
        jPanel7.add(cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 110, -1));

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel38.setForeground(new java.awt.Color(102, 102, 102));
        jLabel38.setText("CPF");
        jPanel7.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, -1, 20));

        Fotu.setFont(new java.awt.Font("Tahoma", 1, 11));
        Fotu.setText("Foto padrão.");
        jPanel7.add(Fotu, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 10, 20));

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel39.setForeground(new java.awt.Color(102, 102, 102));
        jLabel39.setText("Data de Nascimento");
        jPanel7.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 130, 20));

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setFont(new java.awt.Font("Tahoma", 3, 11));
        jButton9.setForeground(new java.awt.Color(255, 51, 0));
        jButton9.setText("Selecionar!");
        jButton9.setToolTipText("Selecionar Foto");
        jButton9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton9.setContentAreaFilled(false);
        jButton9.setNextFocusableComponent(Confirmar);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 130, 40));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 620, 210));

        Ultimo1.setBackground(new java.awt.Color(255, 255, 255));
        Ultimo1.setFont(new java.awt.Font("Tahoma", 1, 18));
        Ultimo1.setForeground(new java.awt.Color(255, 51, 0));
        Ultimo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mectex/imagens/ultimo_32x32.png"))); // NOI18N
        Ultimo1.setToolTipText("Ultimo");
        Ultimo1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Ultimo1.setBorderPainted(false);
        Ultimo1.setContentAreaFilled(false);
        Ultimo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Ultimo1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Ultimo1MouseExited(evt);
            }
        });
        Ultimo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ultimo1ActionPerformed(evt);
            }
        });
        jPanel1.add(Ultimo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 440, 40, 40));

        Proximo1.setBackground(new java.awt.Color(255, 255, 255));
        Proximo1.setFont(new java.awt.Font("Tahoma", 1, 18));
        Proximo1.setForeground(new java.awt.Color(255, 51, 0));
        Proximo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mectex/imagens/proximo_32x32.png"))); // NOI18N
        Proximo1.setToolTipText("Proximo");
        Proximo1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Proximo1.setBorderPainted(false);
        Proximo1.setContentAreaFilled(false);
        Proximo1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Proximo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Proximo1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Proximo1MouseExited(evt);
            }
        });
        Proximo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Proximo1ActionPerformed(evt);
            }
        });
        jPanel1.add(Proximo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, 40, 40));

        Anterior1.setBackground(new java.awt.Color(255, 255, 255));
        Anterior1.setFont(new java.awt.Font("Tahoma", 1, 18));
        Anterior1.setForeground(new java.awt.Color(255, 51, 0));
        Anterior1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mectex/imagens/anterior_32x32.png"))); // NOI18N
        Anterior1.setToolTipText("Anterior");
        Anterior1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Anterior1.setBorderPainted(false);
        Anterior1.setContentAreaFilled(false);
        Anterior1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Anterior1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Anterior1MouseExited(evt);
            }
        });
        Anterior1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Anterior1ActionPerformed(evt);
            }
        });
        jPanel1.add(Anterior1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, 40, 40));

        Primeiro1.setBackground(new java.awt.Color(255, 255, 255));
        Primeiro1.setFont(new java.awt.Font("Tahoma", 1, 18));
        Primeiro1.setForeground(new java.awt.Color(255, 51, 0));
        Primeiro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mectex/imagens/primeiro_32x32.png"))); // NOI18N
        Primeiro1.setToolTipText("Primeiro");
        Primeiro1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Primeiro1.setBorderPainted(false);
        Primeiro1.setContentAreaFilled(false);
        Primeiro1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Primeiro1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Primeiro1MouseExited(evt);
            }
        });
        Primeiro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Primeiro1ActionPerformed(evt);
            }
        });
        jPanel1.add(Primeiro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 40, 40));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados adcionais.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(255, 51, 0))); // NOI18N
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel51.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel51.setForeground(new java.awt.Color(102, 102, 102));
        jLabel51.setText("Extras");
        jPanel13.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 40, 20));

        email1.setFont(new java.awt.Font("Tahoma", 1, 11));
        email1.setToolTipText("Digite o endereço do cliente ");
        jPanel13.add(email1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 200, -1));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel36.setForeground(new java.awt.Color(102, 102, 102));
        jLabel36.setText("Web Site");
        jPanel13.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 60, 20));

        site.setFont(new java.awt.Font("Tahoma", 1, 11));
        site.setToolTipText("Digite o endereço do cliente ");
        jPanel13.add(site, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 170, -1));

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel37.setForeground(new java.awt.Color(102, 102, 102));
        jLabel37.setText("Tipo Residencia");
        jPanel13.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 100, 20));

        residencia.setFont(new java.awt.Font("Tahoma", 1, 11));
        residencia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Propria", "Alugada", "Cedida", "Outra..." }));
        residencia.setToolTipText("Tipo de Residencia em que o cliente vive");
        jPanel13.add(residencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 100, -1));

        estadocivil1.setFont(new java.awt.Font("Tahoma", 1, 11));
        estadocivil1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Solteiro(a)", "Casado(a)", "Viuvo(a)" }));
        estadocivil1.setToolTipText("Estado Civil do Cliente");
        jPanel13.add(estadocivil1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 100, -1));

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel43.setForeground(new java.awt.Color(102, 102, 102));
        jLabel43.setText("Estado civil");
        jPanel13.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 80, 20));

        jLabel52.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel52.setForeground(new java.awt.Color(102, 102, 102));
        jLabel52.setText("Email");
        jPanel13.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 40, 20));

        extra.setColumns(20);
        extra.setFont(new java.awt.Font("Tahoma", 1, 12));
        extra.setRows(5);
        extra.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(extra);

        jPanel13.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 480, 70));

        jPanel1.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 620, 160));

        Confirmar.setBackground(new java.awt.Color(255, 255, 255));
        Confirmar.setFont(new java.awt.Font("Tahoma", 3, 11));
        Confirmar.setForeground(new java.awt.Color(255, 51, 0));
        Confirmar.setText("Confirmar Cadastro");
        Confirmar.setToolTipText("Selecionar Foto");
        Confirmar.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        Confirmar.setContentAreaFilled(false);
        Confirmar.setEnabled(false);
        Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarActionPerformed(evt);
            }
        });
        jPanel1.add(Confirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, 130, 40));

        editar.setBackground(new java.awt.Color(255, 255, 255));
        editar.setFont(new java.awt.Font("Tahoma", 3, 11));
        editar.setForeground(new java.awt.Color(255, 51, 0));
        editar.setText("Editar Cliente");
        editar.setToolTipText("Selecionar Foto");
        editar.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        editar.setContentAreaFilled(false);
        editar.setNextFocusableComponent(excluir);
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });
        jPanel1.add(editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 230, 130, 40));

        jButton12.setBackground(new java.awt.Color(255, 255, 255));
        jButton12.setFont(new java.awt.Font("Tahoma", 3, 11));
        jButton12.setForeground(new java.awt.Color(255, 51, 0));
        jButton12.setText("Novo cliente");
        jButton12.setToolTipText("Para efetuar um novo cadastro , clique aqui!");
        jButton12.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jButton12.setContentAreaFilled(false);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, 130, 40));

        jButton13.setBackground(new java.awt.Color(255, 255, 255));
        jButton13.setFont(new java.awt.Font("Tahoma", 3, 11));
        jButton13.setForeground(new java.awt.Color(255, 51, 0));
        jButton13.setText("Consultar Cliente");
        jButton13.setToolTipText("Selecionar Foto");
        jButton13.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jButton13.setContentAreaFilled(false);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, 130, 40));

        excluir.setBackground(new java.awt.Color(255, 255, 255));
        excluir.setFont(new java.awt.Font("Tahoma", 3, 11));
        excluir.setForeground(new java.awt.Color(255, 51, 0));
        excluir.setText("Excluir Cliente");
        excluir.setToolTipText("Selecionar Foto");
        excluir.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        excluir.setContentAreaFilled(false);
        excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirActionPerformed(evt);
            }
        });
        jPanel1.add(excluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 280, 130, 40));

        jButton15.setBackground(new java.awt.Color(255, 255, 255));
        jButton15.setFont(new java.awt.Font("Tahoma", 3, 11));
        jButton15.setForeground(new java.awt.Color(255, 51, 0));
        jButton15.setText("Adcionar Campo");
        jButton15.setToolTipText("Adcione novos campos na sua area de cadastro, assim personalizando o seu software!");
        jButton15.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jButton15.setContentAreaFilled(false);
        jButton15.setEnabled(false);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 110, 20));

        jButton16.setBackground(new java.awt.Color(255, 255, 255));
        jButton16.setFont(new java.awt.Font("Tahoma", 3, 11));
        jButton16.setForeground(new java.awt.Color(255, 51, 0));
        jButton16.setText("Relatorio de Clientes");
        jButton16.setToolTipText("Selecionar Foto");
        jButton16.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jButton16.setContentAreaFilled(false);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 330, 130, 40));

        jButton17.setBackground(new java.awt.Color(255, 255, 255));
        jButton17.setFont(new java.awt.Font("Tahoma", 3, 11));
        jButton17.setForeground(new java.awt.Color(255, 51, 0));
        jButton17.setText("Gráfico  de Clientes");
        jButton17.setToolTipText("Selecionar Foto");
        jButton17.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jButton17.setContentAreaFilled(false);
        jPanel1.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 380, 130, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Telefone", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(255, 102, 0));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setMinWidth(50);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(50);
        jTable1.getColumnModel().getColumn(2).setMinWidth(100);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(2).setMaxWidth(100);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, 440, 470));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 6));
        jLabel2.setText(">");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, 10, 490));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1300, 490);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(780, 0, 10, 490);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-796)/2, (screenSize.height-521)/2, 796, 521);
    }// </editor-fold>//GEN-END:initComponents

private void BuscaNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscaNomeActionPerformed
//Seleciona a tabela do banco.
        try {
              stm = (PreparedStatement) con.prepareStatement("select * from cadastro_cliente");
              stm.executeQuery();
              rs = stm.executeQuery();
        } catch (SQLException ex) {
            Logger.getLogger(cadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
        }

//Verifica se está em branco.
        if (BuscaNome.getText().equals(""))
        {
        JOptionPane.showMessageDialog(null,"Por Favor Digite o Nome Do Cliente Desejado!","Busca",JOptionPane.WARNING_MESSAGE);
        return;
        }
        
        else{
          try{
             rs.first();
             String igual ="n";
             int tamanho_pesquisa = BuscaNome.getText().length();

       while ( igual.equals("n")){
           String pesquisando = rs.getString("nome").substring(0,(tamanho_pesquisa));
        if(pesquisando.equals(BuscaNome.getText())){igual = "s";}
            else{rs.next();}
        }

	codigo1.setText(rs.getString("codigo"));
	mostrar(rs);

            }
catch(SQLException erro){JOptionPane.showMessageDialog(null,"Nao Foi Localizado os Dados ! \nDica: Caso Seja Um Usuario Nao Cadastrado Efetue Um novo Cadastro");}
           }
}//GEN-LAST:event_BuscaNomeActionPerformed

private void buscaCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaCPFActionPerformed
DestravarCampos();       
}//GEN-LAST:event_buscaCPFActionPerformed

private void masculinoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_masculinoItemStateChanged
sexualidade = "Masculino";    
}//GEN-LAST:event_masculinoItemStateChanged

private void femininoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_femininoItemStateChanged
sexualidade = "Feminino";       
}//GEN-LAST:event_femininoItemStateChanged

private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_nomeActionPerformed

private void Ultimo1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ultimo1MouseEntered
        
}//GEN-LAST:event_Ultimo1MouseEntered

private void Ultimo1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ultimo1MouseExited
        
}//GEN-LAST:event_Ultimo1MouseExited

private void Ultimo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ultimo1ActionPerformed
try{

         stm = (PreparedStatement) con.prepareStatement("select * from cadastro_cliente");
           rs = stm.executeQuery();
           rs.last();

           navega = 2;

            mostrar(rs);

             Ultimo1.setEnabled(false);
             Proximo1.setEnabled(false);
             Primeiro1.setEnabled(true);
             Anterior1.setEnabled(true);
        } catch(SQLException erro){
            
        }
}//GEN-LAST:event_Ultimo1ActionPerformed

private void Proximo1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Proximo1MouseEntered
        
}//GEN-LAST:event_Proximo1MouseEntered

private void Proximo1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Proximo1MouseExited
        
}//GEN-LAST:event_Proximo1MouseExited

private void Proximo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Proximo1ActionPerformed
try{
         rs.next();
           navega = 2;
            mostrar(rs);
             Anterior1.setEnabled(true);
             Primeiro1.setEnabled(true);
  
        } catch(SQLException erro){
          
        }    // TODO add your handling code here:
}//GEN-LAST:event_Proximo1ActionPerformed

private void Anterior1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Anterior1MouseEntered
        
}//GEN-LAST:event_Anterior1MouseEntered

private void Anterior1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Anterior1MouseExited
        
}//GEN-LAST:event_Anterior1MouseExited

private void Primeiro1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Primeiro1MouseEntered
        
}//GEN-LAST:event_Primeiro1MouseEntered

private void Primeiro1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Primeiro1MouseExited
        
}//GEN-LAST:event_Primeiro1MouseExited

private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
if(novo==0){
    DestravarCampos();
editar.setText("Editar Cliente");
edit = 0;
//Limpar Campos
extra.setText("");
BuscaNome.setText("");
buscaCPF.setText("");
nome.setText("");
Fotu.setText("H:/MecTex/src/br/com/mectex/imagens/Addon.png");
codigo1.setText("");
endereco.setText("");
cep.setText("");
bairro.setText("");
numero.setText("");
celular.setText("");
rg.setText("");
cpf.setText("");
telefone.setText("");
cidade.setText("");
nascimento.setText("");
email1.setText("");
site.setText("");

//Adciona a imagem a foto e captura a data
fotux.setIcon( new ImageIcon("H:/MecTex/src/br/com/mectex/imagens/Addon.png"));
registro.setText(""+data.getDate()+"/"+(data.getMonth()+1)+"/"+(data.getYear()+1900));
Proximo1.setEnabled(false);
Anterior1.setEnabled(false);
Ultimo1.setEnabled(false);
Primeiro1.setEnabled(false);
novo=1;
jButton12.setText("Cancelar cadastro");
Confirmar.setEnabled(true);
}
 else{
    novo=0;
    jButton12.setText("Novo cliente");
    Proximo1.setEnabled(true);
Anterior1.setEnabled(true);
Ultimo1.setEnabled(true);
Primeiro1.setEnabled(true);
Confirmar.setEnabled(false);
            try {
                rs.first();
            } catch (SQLException ex) {
                Logger.getLogger(cadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
navega = 1;
  mostrar(rs);

 }
}//GEN-LAST:event_jButton12ActionPerformed

private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
//Abre o JFileChooser
    try{
   JFileChooser buscar_foto = new JFileChooser(); 
   buscar_foto.setCurrentDirectory(new File("B:/"));
   buscar_foto.setDialogTitle("Carregar foto do cliente");
   buscar_foto.showOpenDialog(this);
   
   //Pega o url da imagem e troka a barra
     foto = ""+buscar_foto.getSelectedFile();
     foto = foto.replaceAll("\\\\", "/");
      
       //verifica se foi selecionado uma imagem 
       if ((foto.length() < 4) ||  !foto.contains(".")) 
        {

           Fotu.setText("Foto padrão.");
           fotux.setIcon( new ImageIcon("H:/MecTex/src/br/com/mectex/imagens/Addon.png"));
           foto = "H:/MecTex/src/br/com/mectex/imagens/Addon.png";
        }
           
       
       else{
           
       Image img = Toolkit.getDefaultToolkit().getImage(foto);  
       Image menor = img.getScaledInstance(124, 144, Image.SCALE_DEFAULT);  
       fotux.setIcon(new ImageIcon(menor));
        Fotu.setText(foto);
           
       }


}
  catch(Exception erro){
  }
}//GEN-LAST:event_jButton9ActionPerformed

private void ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarActionPerformed
//Verifica se existe campos vazios      
    if( objtoVerf.Verificação(nome.getText(), endereco.getText(), bairro.getText(), numero.getText(), cidade.getText(), "Sexualidade").equals("Yes"))
{
    //Caso for digitado o email verifica se é valido
    if(objtoVerf.validate(email1.getText()).equals("Valido"))
   {
       //Inseri os dados a tabela 
     try{
String sql_insrt ="insert into cadastro_cliente (nome, `end`, cep, bairro, numero, cidade, telefone, uf, celular, rg, cpf, registro, nascimento, `estadoCivil`, residencia, email, website, extra, foto, sexo) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
stm = (PreparedStatement) con.prepareStatement(sql_insrt);
// preenche os valores
stm.setString(1,nome.getText());
stm.setString(2, endereco.getText());
stm.setString(3,cep.getText() );
stm.setString(4,bairro.getText() );
stm.setString(5,numero.getText() );
stm.setString(6,cidade.getText() );
stm.setString(7,telefone.getText());
stm.setString(8,""+uf.getSelectedItem());
stm.setString(9,celular.getText() );
stm.setString(10,rg.getText() );
stm.setString(11,cpf.getText());
stm.setString(12, registro.getText());
stm.setString(13,nascimento.getText() );
stm.setString(14,""+estadocivil1.getSelectedItem() );
stm.setString(15,""+residencia.getSelectedItem() );
stm.setString(16,email1.getText() );
stm.setString(17,site.getText());
stm.setString(18,""+extra.getText());
stm.setString(19,foto);
stm.setString(20,sexualidade);
stm.execute();

JOptionPane.showMessageDialog(this,"Cliente Cadastrado Com Sucesso!","Cadastro de cliente",JOptionPane.WARNING_MESSAGE);

//Seleciona a tabela cadastro_cliente e deixa o cursor no ultimo registro
stm = (PreparedStatement) con.prepareStatement("select * from cadastro_cliente");
stm.executeQuery();

rs = stm.executeQuery();
rs.last();
navega = 2;
mostrar(rs);
//calcularNumero();
Proximo1.setEnabled(true);
Anterior1.setEnabled(true);
Ultimo1.setEnabled(true);
Primeiro1.setEnabled(true);
}

 catch(SQLException erros){
     JOptionPane.showMessageDialog(null,"Erro Ao Gravar Dados! Por Favor Digite Novamente!  "+erros,"Alerta",JOptionPane.WARNING_MESSAGE);
  }   
   }
    else{
        JOptionPane.showMessageDialog(null,"Por favor digite um email valido!","Alerta",JOptionPane.WARNING_MESSAGE);
    }
}
else{
    JOptionPane.showMessageDialog(null,"Por favor digite todos os dados!","Alerta",JOptionPane.WARNING_MESSAGE);
}
}//GEN-LAST:event_ConfirmarActionPerformed

private void cepFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cepFocusGained

}//GEN-LAST:event_cepFocusGained

private void cepFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cepFocusLost


}//GEN-LAST:event_cepFocusLost

private void telefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefoneActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_telefoneActionPerformed

private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jButton15ActionPerformed

private void cepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cepActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_cepActionPerformed

private void excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirActionPerformed
try{
     stm = (PreparedStatement) con.prepareStatement("select * FROM cadastro_cliente WHERE `codigo` = "+codigo1.getText());
     stm.execute();
     
     rs = stm.executeQuery();
     rs.first();
     
String nome = "Tem Certeza Deseja Excluir o Cliente:  "+rs.getString("nome")+" ?";
int opcao_escolhida = JOptionPane.showConfirmDialog(null,nome," Exclusão",JOptionPane.YES_NO_OPTION);

if ( opcao_escolhida == JOptionPane.YES_OPTION){
stm = (PreparedStatement) con.prepareStatement("DELETE FROM cadastro_cliente WHERE `codigo` = "+codigo1.getText());
stm.execute();

JOptionPane.showMessageDialog(null,"Exclusão do cliente realizada com sucesso! ");

stm = (PreparedStatement) con.prepareStatement("select * from cadastro_cliente");
stm.executeQuery();

rs = stm.executeQuery();
rs.first();


 navega = 1;
 mostrar(rs);
 
   Primeiro1.setEnabled(false);
   Anterior1.setEnabled(false);
   Ultimo1.setEnabled(true);
   Proximo1.setEnabled(true);

}

else{
 return;
    }
  }
catch (SQLException e) {
 throw new RuntimeException(e);
 }
}//GEN-LAST:event_excluirActionPerformed

private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
if(edit == 1){
            try {
                if (verificarAlteracao() == true) {
                    EditarCadastro();
                }
 else{
     return;
 }
            } catch (SQLException ex) {
                Logger.getLogger(cadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
}
else{
    
    edit = 1;
    editar.setText("Confirmar Alteração");
    DestravarCampos();
}
}//GEN-LAST:event_editarActionPerformed

private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jButton13ActionPerformed

private void Primeiro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Primeiro1ActionPerformed
try{

         stm = (PreparedStatement) con.prepareStatement("select * from cadastro_cliente");
          rs = stm.executeQuery();
          rs.first();
               navega = 1;
               mostrar(rs);
               Primeiro1.setEnabled(false);
               Anterior1.setEnabled(false);
               Ultimo1.setEnabled(true);
               Proximo1.setEnabled(true);
  
        } catch(SQLException erro){

        }
}//GEN-LAST:event_Primeiro1ActionPerformed

private void Anterior1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Anterior1ActionPerformed
try{
    
           rs.previous();
           navega = 1;
            mostrar(rs);
               Ultimo1.setEnabled(true);
               Proximo1.setEnabled(true);
  
        } catch(SQLException erro){

        }
}//GEN-LAST:event_Anterior1ActionPerformed

private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
    this.setModal(false);
    ChamarRelatorio relatorio = new ChamarRelatorio(new javax.swing.JFrame(),true);
    relatorio.setVisible(true);
    relatorio.repaint();
    relatorio.validate();
}//GEN-LAST:event_jButton16ActionPerformed

private void masculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masculinoActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_masculinoActionPerformed

private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked

        
    if(barra == 0){
          this.setSize(1260, 518);
         this.repaint();
         this.validate();
         jPanel1.setSize(1260, 518);
         jLabel2.setText("<");
         this.repaint();
         this.validate();
            try {
                PreencherDados();
            } catch (SQLException ex) {
                Logger.getLogger(cadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1260)/2, (screenSize.height-518)/2, 1260, 518);
      barra=1;
    }
 else{
         this.setSize(795, 518);
         this.repaint();
         this.validate();
         jPanel1.setSize(795, 518);
         jLabel2.setText(">");
         this.repaint();
         this.validate();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-795)/2, (screenSize.height-518)/2, 795, 518);
            barra=0;
 }



         
}//GEN-LAST:event_jLabel2MouseClicked

private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
          int linha = jTable1.getSelectedRow();
         int codigo;
        String codigoRecebido;
        codigoRecebido = ""+((DefaultTableModel)jTable1.getModel()).getValueAt(linha,0).toString();
        codigo = Integer.parseInt(codigoRecebido);

         //Seleciona a tabela do banco.
        try {
              stm = (PreparedStatement) con.prepareStatement("select * from cadastro_cliente");
              stm.executeQuery();
              rs = stm.executeQuery();
        } catch (SQLException ex) {
            Logger.getLogger(cadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
        }


          try{
            rs.first();
             String igual ="n";

             int tamanho_pesquisa = codigo;
             
        while (igual.equals("n"))
        {
       int pesquisando = rs.getInt("codigo");
        if(pesquisando==codigo)
            {igual = "s";}
            else{rs.next();}
        }
	codigo1.setText(rs.getString("codigo"));
	mostrar(rs);

            }
catch(SQLException erro){JOptionPane.showMessageDialog(null,"Nao Foi Localizado os Dados ! \nDica: Caso Seja Um Usuario Nao Cadastrado Efetue Um novo Cadastro");}

}//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
             try {
      UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
    } catch(Exception e) {
      System.out.println("Error setting native LAF: " + e);
    }
             java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                cadastroCliente dialog = new cadastroCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Anterior1;
    private javax.swing.JTextField BuscaNome;
    private javax.swing.JButton Confirmar;
    private javax.swing.JLabel Fotu;
    private javax.swing.JButton Primeiro1;
    private javax.swing.JButton Proximo1;
    private javax.swing.JButton Ultimo1;
    private javax.swing.JTextField bairro;
    private javax.swing.JFormattedTextField buscaCPF;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JFormattedTextField celular;
    private javax.swing.JFormattedTextField cep;
    private javax.swing.JTextField cidade;
    private javax.swing.JTextField codigo1;
    private javax.swing.JFormattedTextField cpf;
    private javax.swing.JButton editar;
    private javax.swing.JTextField email1;
    private javax.swing.JTextField endereco;
    private javax.swing.JComboBox estadocivil1;
    private javax.swing.JButton excluir;
    private javax.swing.JTextArea extra;
    private javax.swing.JRadioButton feminino;
    private javax.swing.JLabel fotux;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton masculino;
    private javax.swing.JFormattedTextField nascimento;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField numero;
    private javax.swing.JTextField registro;
    private javax.swing.JComboBox residencia;
    private javax.swing.JFormattedTextField rg;
    private javax.swing.JTextField site;
    private javax.swing.JFormattedTextField telefone;
    private javax.swing.JComboBox uf;
    // End of variables declaration//GEN-END:variables
    public boolean verificarAlteracao() throws SQLException{
int i;
obDados.setNome(rs.getString("nome"));
obDados.setEndereco(rs.getString("end"));
obDados.setCep(rs.getString("cep"));
obDados.setBairro(rs.getString("bairro"));
obDados.setNumero(Integer.parseInt(rs.getString("numero")));
obDados.setCidade(rs.getString("cidade"));
obDados.setTelefone(rs.getString("telefone"));
obDados.setUf(rs.getString("uf"));
obDados.setCelular(rs.getString("celular"));
obDados.setRg(rs.getString("rg"));
obDados.setCpf(rs.getString("cpf"));
obDados.setRegistro(rs.getString("registro"));
obDados.setNascimento(rs.getString("nascimento"));
obDados.setEstadocivil1(rs.getString("estadoCivil"));
obDados.setResidencia(rs.getString("residencia"));
obDados.setEmail1(rs.getString("email"));
obDados.setSite(rs.getString("website"));
obDados.setExtra(rs.getString("extra"));
obDados.setFotu(rs.getString("foto"));
obDados.setSexualidade(rs.getString("sexo"));

if(nome.getText().equals(obDados.getNome()) && endereco.getText().equals(obDados.getEndereco()) && cep.getText().equals(obDados.getCep()) && bairro.getText().equals(obDados.getBairro()) && Integer.parseInt(numero.getText())==obDados.getNumero() && cidade.getText().equals(obDados.getCidade()) && telefone.getText().equals(obDados.getTelefone())  && celular.getText().equals(obDados.getCelular()) && rg.getText().equals(obDados.getRg())  && cpf.getText().equals(obDados.getCpf())  && nascimento.getText().equals(obDados.getNascimento()) ){

  i= JOptionPane.showConfirmDialog(null,"<html><b>Não foram encontradas alteração nos dados principais! \n<html><b>Deseja Continuar a edição?</b></html>","Cadastro de cliente",JOptionPane.INFORMATION_MESSAGE);
   if(i==0){
       return true;
   }
    JOptionPane.showMessageDialog(null,"<html><b>Edição cancelada pelo usúario!!</b></html>","Cadastro de cliente",JOptionPane.INFORMATION_MESSAGE);
    travarCampos();
    editar.setText("Editar Cliente");
    edit=0;
    return false;
}
return true;
    }




    public void travarCampos(){
nome.setEnabled(false);
Fotu.setEnabled(false);
endereco.setEnabled(false);
cep.setEnabled(false);
bairro.setEnabled(false);
numero.setEnabled(false);
celular.setEnabled(false);
rg.setEnabled(false);
cpf.setEnabled(false);
telefone.setEnabled(false);
cidade.setEnabled(false);
nascimento.setEnabled(false);;
email1.setEnabled(false);
site.setEnabled(false);
uf.setEnabled(false);
extra.setEnabled(false);
feminino.setEnabled(false);
masculino.setEnabled(false);
jButton9.setEnabled(false);
estadocivil1.setEnabled(false);
residencia.setEnabled(false);
codigo1.setEnabled(false);

    }


    public void DestravarCampos(){
nome.setEnabled(true);
Fotu.setEnabled(true);
endereco.setEnabled(true);
cep.setEnabled(true);
bairro.setEnabled(true);
numero.setEnabled(true);
celular.setEnabled(true);
rg.setEnabled(true);
cpf.setEnabled(true);
telefone.setEnabled(true);
cidade.setEnabled(true);
nascimento.setEnabled(true);;
email1.setEnabled(true);
site.setEnabled(true);
uf.setEnabled(true);
extra.setEnabled(true);
feminino.setEnabled(true);
masculino.setEnabled(true);
jButton9.setEnabled(true);
estadocivil1.setEnabled(true);
residencia.setEnabled(true);
    }
public void PreencherDados() throws SQLException{
    stm = (PreparedStatement) con.prepareStatement("select * from cadastro_cliente");
    rs = stm.executeQuery();

    DefaultTableModel modelo = (DefaultTableModel)jTable1.getModel();
    modelo.setNumRows(0);
    try{
        while (rs.next())
            modelo.addRow(new Object[]{rs.getString("codigo"),rs.getString("nome"),rs.getString("telefone"),rs.getString("email")});

        }
    catch (SQLException erro){
       System.out.print(erro);
    }
}
   public void mostrar(ResultSet rs){
        try {

                           
codigo1.setText(rs.getString("codigo"));
nome.setText(rs.getString("nome"));
endereco.setText(rs.getString("end"));
cep.setText(rs.getString("cep"));
bairro.setText(rs.getString("bairro"));
numero.setText(rs.getString("numero"));
cidade.setText(rs.getString("cidade"));
telefone.setText(rs.getString("telefone"));
uf.setSelectedItem(rs.getString("uf"));
celular.setText(rs.getString("celular"));
rg.setText(rs.getString("rg"));
cpf.setText(rs.getString("cpf"));
registro.setText(rs.getString("registro"));
nascimento.setText(rs.getString("nascimento"));
estadocivil1.setSelectedItem(rs.getString("estadoCivil"));
residencia.setSelectedItem(rs.getString("residencia"));
email1.setText(rs.getString("email"));
site.setText(rs.getString("website"));
extra.setText(rs.getString("extra"));

    //Adciona img modificando o tamanho
  Image img = Toolkit.getDefaultToolkit().getImage(""+rs.getString("foto"));  
  Image menor = img.getScaledInstance(124, 144, Image.SCALE_DEFAULT);  
  fotux.setIcon(new ImageIcon(menor));

Fotu.setText(rs.getString("foto"));
sexualidade= rs.getString("sexo");

if ( sexualidade.equals("Feminino")){
    feminino.setSelected(rootPaneCheckingEnabled);
}
 else {
    masculino.setSelected(rootPaneCheckingEnabled);
 }



        } catch (SQLException ex) {
           
            
            
            if (navega == 1){
            Primeiro1.setEnabled(false);
            Anterior1.setEnabled(false);
            try {
                 this.rs.next();
                              
                
            }catch (SQLException ex1) {
            navega = 1;
            mostrar(this.rs);
            
            }
           
                 }
                else if(navega == 2){
                    //2
            Ultimo1.setEnabled(false);
            Proximo1.setEnabled(false);
            try {
                this.rs.previous();}
            
            catch (SQLException ex1) 
                {
                      navega = 2;
                     mostrar(this.rs);
                }
           
                }
                else
             
              navega = 0;
            //Logger.getLogger(cadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
        }


 }

   public void EditarCadastro(){



 //inseri os dados na tabela do banco
 String sql = "update cadastro_cliente set nome=?, `end`=?, cep=?, bairro=?, numero=?, cidade=?, telefone=?, uf=?, celular=?, rg=?, cpf=?, registro=?, nascimento=?, `estadoCivil`=?, residencia=?, email=?, website=?, extra=?, foto=?, sexo=? where codigo =?";

 try {
 stm = (PreparedStatement) con.prepareStatement(sql);
stm.setString(1,nome.getText());
stm.setString(2, endereco.getText());
stm.setString(3,cep.getText() );
stm.setString(4,bairro.getText() );
stm.setString(5,numero.getText() );
stm.setString(6,cidade.getText() );
stm.setString(7,telefone.getText());
stm.setString(8,""+uf.getSelectedItem());
stm.setString(9,celular.getText() );
stm.setString(10,rg.getText() );
stm.setString(11,cpf.getText());
stm.setString(12, registro.getText());
stm.setString(13,nascimento.getText() );
stm.setString(14,""+estadocivil1.getSelectedItem() );
stm.setString(15,""+residencia.getSelectedItem() );
stm.setString(16,email1.getText() );
stm.setString(17,site.getText());
stm.setString(18,""+extra.getText());
stm.setString(19,Fotu.getText());
stm.setString(20,sexualidade);
stm.setString(21,codigo1.getText());
stm.execute();
stm.close();
JOptionPane.showMessageDialog(this,"<html><b>Alteração realizada com sucesso</b></html>","Alterar",JOptionPane.WARNING_MESSAGE);
edit = 0;
editar.setText("Editar Cliente");
travarCampos();

//Direciona o cursor
stm = (PreparedStatement) con.prepareStatement("select * from cadastro_cliente");
stm.executeQuery();
rs = stm.executeQuery();
rs.last();
navega = 2;
mostrar(rs);
 Primeiro1.setEnabled(true);
               Anterior1.setEnabled(true);
               Ultimo1.setEnabled(false);
               Proximo1.setEnabled(false);
 } catch (SQLException e) {
 throw new RuntimeException(e);
 }
   }
}

