import javax.swing.JOptionPane;
/*
 * FCadSetor.java
 *
 * Created on 29 de Novembro de 2005, 14:56
 */

/**
 *
 * @author  rodrigo.tavares
 */
public class FCadSetor extends javax.swing.JFrame {
    
    /** Creates new form FCadSetor */
    public FCadSetor() {
        initComponents();
        setBounds(100,100,410,290);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        getContentPane().setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciador de Di\u00e1rias ASTEC-PB v1.0");
        setResizable(false);
        jPanel1.setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.setFont(new java.awt.Font("MS Sans Serif", 1, 12));
        jLabel1.setText("Cadastro de Setor");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(130, 0, 130, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 380, 30);

        jPanel2.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel2.setText("Nome do Setor:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 10, 90, 15);

        jLabel3.setText("Descri\u00e7\u00e3o do Setor:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 50, 120, 15);

        jPanel2.add(txtNome);
        txtNome.setBounds(10, 30, 240, 20);

        txtDescricao.setColumns(20);
        txtDescricao.setRows(5);
        jScrollPane1.setViewportView(txtDescricao);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 70, 240, 60);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 50, 380, 150);

        jPanel3.setLayout(null);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        jPanel3.add(btnSalvar);
        btnSalvar.setBounds(80, 10, 100, 23);

        btnCancelar.setText("Cancelar");
        jPanel3.add(btnCancelar);
        btnCancelar.setBounds(180, 10, 100, 23);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(10, 210, 380, 40);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
// TODO add your handling code here:
        if(txtNome.getText().trim().length() == 0 || txtDescricao.getText().trim().length() == 0){
         JOptionPane.showMessageDialog(null,"Preencha os campos","ATENÇÃO",JOptionPane.WARNING_MESSAGE);
         }else{
        ClassCadSetor setor = new ClassCadSetor();
        setor.setNome(txtNome.getText());
        setor.setDescricao(txtDescricao.getText());
        setor.CadastraSetor();
        }
    }//GEN-LAST:event_btnSalvarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FCadSetor().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtDescricao;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
    
}
