import javax.swing.JOptionPane;
/*
 * FCadUser.java
 *
 * Created on 14 de Dezembro de 2005, 14:02
 */

/**
 *
 * @author  rodrigo.tavares
 */
public class FCadUser extends javax.swing.JFrame {
    
    /** Creates new form FCadUser */
    public FCadUser() {
        initComponents();
        setBounds(250,250,410,220);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        getContentPane().setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciador de Di\u00e1rias ASTEC-PB v1.0");
        setResizable(false);
        jPanel1.setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.setFont(new java.awt.Font("MS Sans Serif", 1, 12));
        jLabel1.setText("Cadastro de Usu\u00e1rios");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(120, 10, 123, 16);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 380, 40);

        jPanel2.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel2.setText("Digite o Login:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 10, 110, 15);

        jLabel3.setText("Digite a Senha:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 40, 100, 15);

        jPanel2.add(txtUser);
        txtUser.setBounds(110, 10, 150, 20);

        jPanel2.add(txtSenha);
        txtSenha.setBounds(110, 40, 150, 22);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 60, 380, 70);

        jPanel3.setLayout(null);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        jPanel3.add(btnSalvar);
        btnSalvar.setBounds(180, 10, 100, 23);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jPanel3.add(btnCancelar);
        btnCancelar.setBounds(80, 10, 100, 23);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(10, 140, 378, 40);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
// TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
// TODO add your handling code here:
  
        if(txtUser.getText().length() == 0 || txtSenha.getPassword().length == 0 ){        
         JOptionPane.showMessageDialog(null,"Preencha os campos","ATENÇÃO",JOptionPane.WARNING_MESSAGE);         
        }else{
        ClassCadUsuario usuario = new ClassCadUsuario();
        usuario.setUsuario(txtUser.getText(), txtSenha.getText());
        usuario.incluiUsuario();
        }
    }//GEN-LAST:event_btnSalvarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FCadUser().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
    
}
