/*
 * FNovaDiaria.java
 *
 * Created on 8 de Novembro de 2005, 14:00
 */

/**
 *
 * @author  rodrigo.tavares
 */
import java.sql.*;
import javax.swing.JOptionPane;
public class FNovaDiaria extends javax.swing.JFrame {
    
       
    /** Creates new form FNovaDiaria */
    public FNovaDiaria() {
        initComponents();
        //Posição que a tela vai sair(100,100)/Lado Direito(470)/Lado Esquerdo(500)
        setBounds(100,100,475,430);       
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MemoDestino = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        MemoObjetivo = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ComboSetor = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPeriodoSaida = new javax.swing.JTextField();
        txtPeriodoChegada = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        MemoObs = new javax.swing.JTextArea();
        txtQtdDiaria = new javax.swing.JTextField();
        ComboRelatorio = new javax.swing.JComboBox();
        CBNome = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciador de Diárias ASTEC-PB v1.0");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setLayout(null);

        btnSalvar.setText("Salvar");
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalvarMouseClicked(evt);
            }
        });
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalvar);
        btnSalvar.setBounds(120, 10, 100, 23);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar);
        btnCancelar.setBounds(230, 10, 90, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 360, 450, 40);

        jLabel7.setFont(new java.awt.Font("MS Sans Serif", 1, 14));
        jLabel7.setText("Cadastro de Nova Diária:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(120, 10, 173, 19);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setMinimumSize(new java.awt.Dimension(745, 100));
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("MS Sans Serif", 1, 11));
        jLabel4.setText("Destino:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 200, 60, 15);

        MemoDestino.setColumns(20);
        MemoDestino.setRows(5);
        MemoDestino.setToolTipText("Informe o destino da Diária");
        jScrollPane1.setViewportView(MemoDestino);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 220, 206, 82);

        jLabel6.setFont(new java.awt.Font("MS Sans Serif", 1, 11));
        jLabel6.setText("Objetivo:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(240, 100, 70, 15);

        MemoObjetivo.setColumns(20);
        MemoObjetivo.setRows(5);
        MemoObjetivo.setToolTipText("Informe alguma observação");
        jScrollPane2.setViewportView(MemoObjetivo);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(230, 220, 210, 80);

        jLabel9.setFont(new java.awt.Font("MS Sans Serif", 1, 11));
        jLabel9.setText("Qtd. Diárias:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 150, 80, 15);

        jLabel5.setFont(new java.awt.Font("MS Sans Serif", 1, 11));
        jLabel5.setText("Relatório:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(130, 150, 70, 15);

        jLabel1.setFont(new java.awt.Font("MS Sans Serif", 1, 11));
        jLabel1.setText("Nome do Servidor:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 20, 110, 15);

        ComboSetor.setToolTipText("Selecione um Setor");
        jPanel2.add(ComboSetor);
        ComboSetor.setBounds(10, 80, 130, 20);

        jLabel8.setFont(new java.awt.Font("MS Sans Serif", 1, 11));
        jLabel8.setText("Setor do Servidor:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 60, 120, 15);

        jLabel2.setFont(new java.awt.Font("MS Sans Serif", 1, 11));
        jLabel2.setText("Data de Saída:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 100, 110, 15);

        txtPeriodoSaida.setToolTipText("Informe à data de Saída");
        jPanel2.add(txtPeriodoSaida);
        txtPeriodoSaida.setBounds(10, 120, 100, 20);

        txtPeriodoChegada.setToolTipText("Informe à data de Chegada");
        jPanel2.add(txtPeriodoChegada);
        txtPeriodoChegada.setBounds(120, 120, 110, 20);

        jLabel3.setFont(new java.awt.Font("MS Sans Serif", 1, 11));
        jLabel3.setText("Data de Chegada:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(120, 100, 94, 15);

        jLabel10.setFont(new java.awt.Font("MS Sans Serif", 1, 11));
        jLabel10.setText("Observações:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(230, 200, 76, 15);

        MemoObs.setColumns(20);
        MemoObs.setRows(5);
        MemoObs.setToolTipText("Informe o Objetivo da Diária\n");
        jScrollPane3.setViewportView(MemoObs);

        jPanel2.add(jScrollPane3);
        jScrollPane3.setBounds(240, 120, 200, 80);

        txtQtdDiaria.setToolTipText("Informe à Quantidade de Diárias, Só seram aceitos Números");
        jPanel2.add(txtQtdDiaria);
        txtQtdDiaria.setBounds(10, 170, 110, 20);

        ComboRelatorio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DEVENDO", "ENTREGUE" }));
        ComboRelatorio.setToolTipText("Informe à Situação da Diária \n - Opções:\n  - DEVENDO Relatório\n  - Relatório ENTREGUE");
        jPanel2.add(ComboRelatorio);
        ComboRelatorio.setBounds(130, 170, 100, 20);

        CBNome.setToolTipText("Selecione um Servidor");
        jPanel2.add(CBNome);
        CBNome.setBounds(10, 40, 430, 20);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 40, 450, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
// TODO add your handling code here:
        ClassConecta conexao = new ClassConecta();
        try{
          Connection  con = conexao.conecta();
          Statement stmt = con.createStatement();          
          ResultSet rsSetor = stmt.executeQuery("select * from TabCadSetor");          
          while(rsSetor.next()){           
            String setor = rsSetor.getString(2);
            ComboSetor.addItem(setor);
          }          
          rsSetor.close();
          ResultSet rsServidor = stmt.executeQuery("select * from TabServidor");
          while(rsServidor.next()){
              String nome = rsServidor.getString(2);
              CBNome.addItem(nome);
          }
          rsServidor.close();
          stmt.close();
        }catch(SQLException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
// TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
// TODO add your handling code here:        
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void btnSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseClicked
       if(txtPeriodoSaida.getText().trim().length() == 0 ||
          txtPeriodoChegada.getText().trim().length() ==0 ||
          txtQtdDiaria.getText().trim().length() == 0 ||
          MemoDestino.getText().trim().length() == 0 ||
          MemoObjetivo.getText().trim().length() == 0 ||
          MemoObs.getText().trim().length() == 0){
         //MEnsagem de Alerta  
         JOptionPane.showMessageDialog(null,"Todos os Campos devem ser preenchidos","ATENÇÃO",JOptionPane.WARNING_MESSAGE);
      }else{
        //Variaveis para receber os valores do form
        String nome = CBNome.getSelectedItem().toString();
        String setor = ComboSetor.getSelectedItem().toString();
        String periodoSaida = txtPeriodoSaida.getText();
        String periodoChegada = txtPeriodoChegada.getText();
        String destino = MemoDestino.getText();
        String objetivo = MemoObjetivo.getText();
        String Obs = MemoObs.getText();        
        String relatorio = ComboRelatorio.getSelectedItem().toString(); // iniciei vazia pois vou tratá-la logo abaixo
       int QtdDiaria = Integer.parseInt(txtQtdDiaria.getText());
        // Fim das Variaveis
       ClassDiaria diaria = new ClassDiaria();      
       diaria.setPegaValDiaria(nome, periodoSaida, periodoChegada, destino, relatorio, setor, objetivo, Obs, QtdDiaria);
       diaria.incluiDiaria();
           }
     
    }//GEN-LAST:event_btnSalvarMouseClicked

private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_btnSalvarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FNovaDiaria().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CBNome;
    private javax.swing.JComboBox ComboRelatorio;
    private javax.swing.JComboBox ComboSetor;
    private javax.swing.JTextArea MemoDestino;
    private javax.swing.JTextArea MemoObjetivo;
    private javax.swing.JTextArea MemoObs;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField txtPeriodoChegada;
    private javax.swing.JTextField txtPeriodoSaida;
    private javax.swing.JTextField txtQtdDiaria;
    // End of variables declaration//GEN-END:variables
    
}
