package com.Sokkyo.Cadastros;

import com.Sokkyo.Consulta.Consulta_Cliente;
import com.Sokkyo.Utilitarios.Conexão.Conexão;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.text.ParseException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.HashMap;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;


public final class Cadastro_de_Clientes extends javax.swing.JFrame {
 Date data = new Date();

 private int navega = 0;

 Conexão software_sokkyo;
 private  String sexualidade = "";
 public String ordenaçao = "cadastro_nome";



    public Cadastro_de_Clientes() {
        initComponents();
        software_sokkyo = new Conexão();
        software_sokkyo.conecta();
     try{
PreencherTable2();
software_sokkyo.executeSQL("select * from cadastro_cliente");
calcularNumero();
PreencherTable();
 software_sokkyo.resultset.first();
 mostrar_dados();
 navega = 1;
         }
     catch(Exception e){

     }
           
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sexo = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        WWW = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        BuscaNome = new javax.swing.JTextField();
        buscaCPF = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        masculino = new javax.swing.JRadioButton();
        feminino = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        fotux = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        codigo1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        bairro = new javax.swing.JTextField();
        cep = new javax.swing.JFormattedTextField();
        numero = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        cidade = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        telefone = new javax.swing.JFormattedTextField();
        jLabel30 = new javax.swing.JLabel();
        celular = new javax.swing.JFormattedTextField();
        jLabel31 = new javax.swing.JLabel();
        rg = new javax.swing.JFormattedTextField();
        jLabel32 = new javax.swing.JLabel();
        nascimento = new javax.swing.JFormattedTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        registro = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        uf = new javax.swing.JComboBox();
        endereco = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        cpf = new javax.swing.JFormattedTextField();
        jLabel38 = new javax.swing.JLabel();
        Fotu = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        site = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        residencia = new javax.swing.JComboBox();
        estadocivil = new javax.swing.JComboBox();
        jLabel42 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Ultimo1 = new javax.swing.JButton();
        Proximo1 = new javax.swing.JButton();
        Anterior1 = new javax.swing.JButton();
        Primeiro1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel14 = new javax.swing.JPanel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        numerodecliente = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        placa = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        foto = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        marca = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        codigo = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        placaC = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        km = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jComboBox8 = new javax.swing.JComboBox();
        modelo = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        jComboBox9 = new javax.swing.JComboBox();
        jComboBox10 = new javax.swing.JComboBox();
        jLabel55 = new javax.swing.JLabel();
        anoFab = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        vistoria = new javax.swing.JFormattedTextField();
        chassi = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        clienteV = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        anoMod1 = new javax.swing.JTextField();
        fc = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel15 = new javax.swing.JPanel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        numerodecliente1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Clientes");
        setBackground(new java.awt.Color(51, 102, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        WWW.setFont(new java.awt.Font("BankGothic Md BT", 1, 12));
        WWW.setForeground(new java.awt.Color(102, 102, 102));
        WWW.setText("www.nokys.com.br");
        WWW.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WWWMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                WWWMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                WWWMouseExited(evt);
            }
        });
        jPanel2.add(WWW, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 190, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 830, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sokkyo/icones/people(2).png"))); // NOI18N
        jButton3.setMnemonic('N');
        jButton3.setText(" Novo");
        jButton3.setToolTipText("Novo Cadastro");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jButton3FocusLost(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 100, 40));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sokkyo/icones/gtk_edit.png"))); // NOI18N
        jButton4.setMnemonic('E');
        jButton4.setText(" Editar");
        jButton4.setToolTipText("Editar o Cadastro");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 6, 110, 40));

        jButton7.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sokkyo/icones/12594410.png"))); // NOI18N
        jButton7.setMnemonic('x');
        jButton7.setText(" Excluir");
        jButton7.setToolTipText("Excluir Cadastro");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 6, 110, 40));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 11));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sokkyo/icones/6155_32x32.png"))); // NOI18N
        jButton6.setMnemonic('c');
        jButton6.setText(" Cancelar");
        jButton6.setToolTipText("Cancelar Cadastro de Cliente");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 130, 140, 40));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sokkyo/icones/ok-32x32.png"))); // NOI18N
        jButton1.setText(" Confirmar");
        jButton1.setToolTipText("Confirmar cadastro de Cliente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, 140, -1));

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 11));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sokkyo/Icons/1408_32x32.png"))); // NOI18N
        jButton10.setText("Procurar");
        jButton10.setToolTipText("Efetuar Busca mais detalhada do cliente");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, 140, 40));

        jButton11.setFont(new java.awt.Font("Tahoma", 1, 11));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sokkyo/Icons/print_icon.gif"))); // NOI18N
        jButton11.setText("Gerar Relatorio");
        jButton11.setToolTipText("Efetuar Busca mais detalhada do cliente");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 230, 140, 40));

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(153, 153, 153))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel23.setText("RG:");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 30, 20));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel24.setText("Nome:");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 40, 20));

        BuscaNome.setFont(new java.awt.Font("Tahoma", 1, 11));
        BuscaNome.setToolTipText("Digite o nome do cliente e aperte 'Enter' para efetuar a busca");
        BuscaNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscaNomeActionPerformed(evt);
            }
        });
        jPanel3.add(BuscaNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 200, -1));

        buscaCPF.setFont(new java.awt.Font("Tahoma", 1, 11));
        buscaCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaCPFActionPerformed(evt);
            }
        });
        jPanel3.add(buscaCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 110, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 430, 50));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sexo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(153, 153, 153))); // NOI18N
        jPanel4.setToolTipText("Escolha o Sexo do cliente");
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sexo.add(masculino);
        masculino.setFont(new java.awt.Font("Tahoma", 1, 12));
        masculino.setText("Masculino");
        masculino.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                masculinoItemStateChanged(evt);
            }
        });
        jPanel4.add(masculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        sexo.add(feminino);
        feminino.setFont(new java.awt.Font("Tahoma", 1, 12));
        feminino.setText("Feminino");
        feminino.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                femininoItemStateChanged(evt);
            }
        });
        jPanel4.add(feminino, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 190, 50));

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados do Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(153, 153, 153))); // NOI18N
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        fotux.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sokkyo/icones/people(3).png"))); // NOI18N
        fotux.setToolTipText("Foto do Cliente *Opcional");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fotux, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fotux, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 130, 130));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel15.setText("Celular:");
        jPanel7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 50, 20));

        nome.setFont(new java.awt.Font("Tahoma", 1, 11));
        nome.setToolTipText("Digite o nome completo do cliente ");
        nome.setNextFocusableComponent(endereco);
        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });
        jPanel7.add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 210, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel18.setText("Nome:");
        jPanel7.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 40, 20));

        codigo1.setFont(new java.awt.Font("Tahoma", 1, 11));
        codigo1.setToolTipText("Codigo do Cliente");
        codigo1.setRequestFocusEnabled(false);
        jPanel7.add(codigo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 100, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel19.setText("Endereço:");
        jPanel7.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 20));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel21.setText("Codigo:");
        jPanel7.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 50, 20));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel26.setText("UF:");
        jPanel7.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 20, 20));

        bairro.setFont(new java.awt.Font("Tahoma", 1, 11));
        jPanel7.add(bairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 100, -1));

        try {
            cep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cep.setToolTipText("");
        cep.setFont(new java.awt.Font("Tahoma", 1, 11));
        jPanel7.add(cep, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 100, -1));

        numero.setFont(new java.awt.Font("Tahoma", 1, 11));
        numero.setToolTipText("Numero da Residencia");
        jPanel7.add(numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 50, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel28.setText("CEP:");
        jPanel7.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 30, 20));

        cidade.setFont(new java.awt.Font("Tahoma", 1, 11));
        cidade.setToolTipText("Cidade onde o cliente mora");
        jPanel7.add(cidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 100, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel29.setText("Bairro:");
        jPanel7.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 50, 20));

        try {
            telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(0##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        telefone.setFont(new java.awt.Font("Tahoma", 1, 11));
        jPanel7.add(telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 100, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel30.setText("Cidade:");
        jPanel7.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 50, 20));

        try {
            celular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        celular.setFont(new java.awt.Font("Tahoma", 1, 11));
        jPanel7.add(celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 100, -1));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel31.setText("Telefone:");
        jPanel7.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 60, 20));

        try {
            rg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        rg.setFont(new java.awt.Font("Tahoma", 1, 11));
        jPanel7.add(rg, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 100, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel32.setText("RG:");
        jPanel7.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 30, 20));

        try {
            nascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        nascimento.setFont(new java.awt.Font("Tahoma", 1, 11));
        jPanel7.add(nascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 100, -1));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel33.setText("Data de Nascimento:");
        jPanel7.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 130, 20));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel34.setText("Registro:");
        jPanel7.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 60, 20));

        registro.setFont(new java.awt.Font("Tahoma", 1, 11));
        registro.setRequestFocusEnabled(false);
        jPanel7.add(registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 100, -1));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel35.setText("Numero");
        jPanel7.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 50, 20));

        uf.setFont(new java.awt.Font("Tahoma", 1, 11));
        uf.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SP", "RJ", "MG", "PA", "PB", "PR", "TO", "AM", "BA", "SC" }));
        uf.setToolTipText("Estado ");
        jPanel7.add(uf, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 50, -1));

        endereco.setFont(new java.awt.Font("Tahoma", 1, 11));
        endereco.setToolTipText("Digite o endereço do cliente ");
        jPanel7.add(endereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 210, 20));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 11));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sokkyo/icones/http___iconesbr.oficinadanet.com_10684_32x32.png"))); // NOI18N
        jButton8.setText("Selecionar");
        jButton8.setToolTipText("Selecionar Foto");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 130, 40));

        try {
            cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cpf.setToolTipText("CPF do Cliente");
        cpf.setFont(new java.awt.Font("Tahoma", 1, 11));
        jPanel7.add(cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 100, -1));

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel38.setText("CPF:");
        jPanel7.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, -1, 20));

        Fotu.setFont(new java.awt.Font("Tahoma", 1, 11));
        Fotu.setText("Foto:");
        jPanel7.add(Fotu, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, -1, 20));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 620, 210));

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados Extras", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(153, 153, 153))); // NOI18N
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel50.setText("Email");
        jPanel13.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 40, 20));

        email.setFont(new java.awt.Font("Tahoma", 1, 11));
        email.setToolTipText("Digite o endereço do cliente ");
        jPanel13.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 200, -1));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel36.setText("Web Site");
        jPanel13.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 60, 20));

        site.setFont(new java.awt.Font("Tahoma", 1, 11));
        site.setToolTipText("Digite o endereço do cliente ");
        jPanel13.add(site, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 170, -1));

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel37.setText("Tipo Residencia");
        jPanel13.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 100, 20));

        residencia.setFont(new java.awt.Font("Tahoma", 1, 11));
        residencia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Propria", "Alugada", "Cedida", "Outra..." }));
        residencia.setToolTipText("Tipo de Residencia em que o cliente vive");
        jPanel13.add(residencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 100, -1));

        estadocivil.setFont(new java.awt.Font("Tahoma", 1, 11));
        estadocivil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Solteiro(a)", "Casado(a)", "Viuvo(a)" }));
        estadocivil.setToolTipText("Estado Civil do Cliente");
        jPanel13.add(estadocivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 100, -1));

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel42.setText("Estado civil");
        jPanel13.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 80, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sokkyo/Icons/16x16_smiley-wink.gif"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel13.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, 20, 20));

        jPanel1.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 620, 80));

        Ultimo1.setFont(new java.awt.Font("Tahoma", 1, 11));
        Ultimo1.setForeground(new java.awt.Color(153, 153, 153));
        Ultimo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sokkyo/icones/ultimo_32x32.png"))); // NOI18N
        Ultimo1.setToolTipText("Ultimo");
        Ultimo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Ultimo1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Ultimo1MouseExited(evt);
            }
        });
        Ultimo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ultimo1ActionPerformed(evt);
            }
        });
        jPanel1.add(Ultimo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, 40, -1));

        Proximo1.setFont(new java.awt.Font("Tahoma", 1, 11));
        Proximo1.setForeground(new java.awt.Color(153, 153, 153));
        Proximo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sokkyo/icones/proximo_32x32.png"))); // NOI18N
        Proximo1.setToolTipText("Proximo");
        Proximo1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Proximo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Proximo1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Proximo1MouseExited(evt);
            }
        });
        Proximo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Proximo1ActionPerformed(evt);
            }
        });
        jPanel1.add(Proximo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, 40, -1));

        Anterior1.setFont(new java.awt.Font("Tahoma", 1, 11));
        Anterior1.setForeground(new java.awt.Color(153, 153, 153));
        Anterior1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sokkyo/icones/anterior_32x32.png"))); // NOI18N
        Anterior1.setToolTipText("Anterior");
        Anterior1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Anterior1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Anterior1MouseExited(evt);
            }
        });
        Anterior1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Anterior1ActionPerformed(evt);
            }
        });
        jPanel1.add(Anterior1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, 40, -1));

        Primeiro1.setFont(new java.awt.Font("Tahoma", 1, 11));
        Primeiro1.setForeground(new java.awt.Color(153, 153, 153));
        Primeiro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sokkyo/icones/primeiro_32x32.png"))); // NOI18N
        Primeiro1.setToolTipText("Primeiro");
        Primeiro1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Primeiro1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Primeiro1MouseExited(evt);
            }
        });
        Primeiro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Primeiro1ActionPerformed(evt);
            }
        });
        jPanel1.add(Primeiro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, 40, -1));

        jTabbedPane1.addTab("Clientes", jPanel1);

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Nome", "Telefone", "RG"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setResizable(false);
        jTable1.getColumnModel().getColumn(1).setResizable(false);
        jTable1.getColumnModel().getColumn(2).setResizable(false);
        jTable1.getColumnModel().getColumn(3).setResizable(false);

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ordenação:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(153, 153, 153))); // NOI18N
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Arial", 1, 11));
        jRadioButton2.setText("Codigo");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel14.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, 20));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Arial", 1, 11));
        jRadioButton1.setText("Nome");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel14.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 20));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 10));
        jLabel16.setText("  Numero de cliente Cadastrados:   ");

        numerodecliente.setFont(new java.awt.Font("Tahoma", 1, 10));
        numerodecliente.setText("0");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numerodecliente, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap(30, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numerodecliente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Clientes Cadastrados", jPanel6);

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar Veiculo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(153, 153, 153))); // NOI18N
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        placa.setFont(new java.awt.Font("Tahoma", 1, 11));
        placa.setToolTipText("Digite a Placa e aperte 'Enter' para efetuar a busca");
        placa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placaActionPerformed(evt);
            }
        });
        jPanel10.add(placa, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 200, -1));

        jLabel51.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel51.setText("Placa:");
        jPanel10.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 40, 20));

        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 470, 50));

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Caracteristicas do Carro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(153, 153, 153))); // NOI18N
        jPanel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel11MouseClicked(evt);
            }
        });
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sokkyo/icones/carros+financiamos+e+aprovamos+cadastro__3BB043_1 - Cópia.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addComponent(foto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(foto, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 450, 210));

        jLabel40.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel40.setText("Portas:");
        jPanel11.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 50, 20));

        marca.setFont(new java.awt.Font("Tahoma", 1, 11));
        marca.setToolTipText("Digite a Marca do Veiculo");
        jPanel11.add(marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 190, -1));

        jLabel41.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel41.setText("Marca:");
        jPanel11.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 40, 20));

        codigo.setFont(new java.awt.Font("Tahoma", 1, 11));
        codigo.setToolTipText("Codigo do Cliente");
        codigo.setRequestFocusEnabled(false);
        jPanel11.add(codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, 100, -1));

        jLabel43.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel43.setText("Codigo:");
        jPanel11.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 50, 20));

        placaC.setFont(new java.awt.Font("Tahoma", 1, 11));
        placaC.setToolTipText("Placa do Veiculo");
        jPanel11.add(placaC, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 80, -1));

        jLabel45.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel45.setText("Vistoria:");
        jPanel11.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 50, 20));

        km.setFont(new java.awt.Font("Tahoma", 1, 11));
        km.setToolTipText("Ano do Modelo do veiculo");
        jPanel11.add(km, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 70, -1));

        jLabel46.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel46.setText("Modelo:");
        jPanel11.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 50, 20));

        jLabel47.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel47.setText("Placa:");
        jPanel11.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 50, 20));

        jLabel49.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel49.setText("Combut:");
        jPanel11.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 50, 20));

        jComboBox8.setFont(new java.awt.Font("Tahoma", 1, 11));
        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "4", "6", "8", "limousine", "Ou sei la Oq..." }));
        jComboBox8.setToolTipText("");
        jPanel11.add(jComboBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, 100, -1));

        modelo.setFont(new java.awt.Font("Tahoma", 1, 11));
        modelo.setToolTipText("Digite o endereço do cliente ");
        modelo.setNextFocusableComponent(clienteV);
        jPanel11.add(modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 90, 20));

        jLabel54.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel54.setText("Estado:");
        jPanel11.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 50, 20));

        jComboBox9.setFont(new java.awt.Font("Tahoma", 1, 11));
        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Novo", "Semi - Novo", "Velho" }));
        jComboBox9.setToolTipText("");
        jPanel11.add(jComboBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 100, 20));

        jComboBox10.setFont(new java.awt.Font("Tahoma", 1, 11));
        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Gasolina", "Alcool", "Disel", "Eletrico", "Outro..." }));
        jComboBox10.setToolTipText("Combustivel do Automovel");
        jPanel11.add(jComboBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 100, -1));

        jLabel55.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel55.setText("Ano Fab.");
        jPanel11.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 50, 20));

        anoFab.setFont(new java.awt.Font("Tahoma", 1, 11));
        anoFab.setToolTipText("Ano da Fabricação");
        jPanel11.add(anoFab, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 90, -1));

        jLabel44.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel44.setText("Chassi");
        jPanel11.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 20));

        try {
            vistoria.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        vistoria.setToolTipText("Ultima Vistoria");
        vistoria.setFont(new java.awt.Font("Tahoma", 1, 11));
        jPanel11.add(vistoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 90, -1));

        chassi.setFont(new java.awt.Font("Tahoma", 1, 11));
        chassi.setToolTipText("Numero do Chassi");
        chassi.setNextFocusableComponent(modelo);
        jPanel11.add(chassi, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 190, 20));

        jLabel48.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel48.setText("Cliente:");
        jPanel11.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 50, 20));

        clienteV.setFont(new java.awt.Font("Tahoma", 1, 11));
        clienteV.setToolTipText("Dono do Automovel");
        jPanel11.add(clienteV, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 160, 20));

        jLabel56.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel56.setText("Ano Mod.");
        jPanel11.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 60, 20));

        jLabel58.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel58.setText("Km");
        jPanel11.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 20, 20));

        anoMod1.setFont(new java.awt.Font("Tahoma", 1, 11));
        anoMod1.setToolTipText("Ano do Modelo do veiculo");
        jPanel11.add(anoMod1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 90, -1));

        fc.setFont(new java.awt.Font("Tahoma", 1, 8));
        fc.setText("Honda Civic");
        fc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel11.add(fc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 440, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sokkyo/Icons/icon_16x16_help.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel11.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 20, 20));

        jPanel9.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 620, 420));

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 11));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sokkyo/icones/http___iconesbr.oficinadanet.com_10684_32x32.png"))); // NOI18N
        jButton9.setText("Selecionar");
        jButton9.setToolTipText("Selecionar Foto");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 130, 40));

        jTabbedPane1.addTab("Veiculo", jPanel9);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Modelo", "Placa", "Marca", "Chassi", "Dono"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 75, 599, 387));

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ordenação:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(153, 153, 153))); // NOI18N
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Arial", 1, 11));
        jRadioButton3.setText("Codigo");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jPanel15.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, 20));

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Arial", 1, 11));
        jRadioButton4.setText("Nome");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        jPanel15.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 20));

        jPanel5.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 19, 176, 50));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 10));
        jLabel17.setText("  Numero de Veiculos Cadastrados:   ");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, 20));

        numerodecliente1.setFont(new java.awt.Font("Tahoma", 1, 10));
        numerodecliente1.setText("0");
        jPanel5.add(numerodecliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 17, 20));

        jTabbedPane1.addTab("Veiculos Cadastrados", jPanel5);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 640, 470));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sokkyo/Icons/LogoNoky.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, -10, 380, 350));

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sokkyo/icones/fechar_32x32.png"))); // NOI18N
        jButton5.setMnemonic('s');
        jButton5.setText(" Sair");
        jButton5.setToolTipText("Sair do Menu Cadastro");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 6, 110, 40));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-827)/2, (screenSize.height-597)/2, 827, 597);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
      try{
    JFileChooser buscar_foto = new JFileChooser();
    buscar_foto.setCurrentDirectory(new File(""));
   buscar_foto.setDialogTitle("Carregar foto do cliente");
    buscar_foto.showOpenDialog(this);
    String foto = "";
     foto = ""+buscar_foto.getSelectedFile();
       foto = foto.replaceAll("\\\\", "/");
      Fotu.setText(foto);
  fotux.setIcon(new ImageIcon(""+Fotu.getText()));


}
  catch(Exception erro){
  }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
if(jTabbedPane1.getSelectedIndex() == (0)){

 BuscaNome.setText("");
buscaCPF.setText("");
nome.setText("");
codigo1.setText("");
endereco.setText("");
cep.setText("");
bairro.setText("");
numero.setText("");
cidade.setText("");
 telefone.setText("");
 celular.setText("");
 rg.setText("");
 cpf.setText("");
 nascimento.setText("");
 email.setText("");
 site.setText("");
 fotux.setIcon( new javax.swing.ImageIcon(getClass().getResource("/icones/people(3).png")));
registro.setText(""+data.getDate()+"/"+(data.getMonth()+1)+"/"+(data.getYear()+1900));

        }
if(jTabbedPane1.getSelectedIndex() == (2)){
     placa.setText("");
     marca.setText("");
     codigo.setText("");
     chassi.setText("");
     modelo.setText("");
     clienteV.setText("");
     anoFab.setText("");
     anoMod1.setText("");
     placaC.setText("");
     km.setText("");
     vistoria.setText("");
     foto.setIcon( new javax.swing.ImageIcon(getClass().getResource("/icones/carros+financiamos+e+aprovamos+cadastro__3BB043_1 - Cópia.jpg")));
 }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton3FocusLost
      
    }//GEN-LAST:event_jButton3FocusLost

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked

    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
if(jTabbedPane1.getSelectedIndex() == (0)){
    software_sokkyo.executeSQL("select * from cadastro_cliente");
if(Verificar().equals("No")){
     if(validate(email.getText()).equals("Valido")){
          try{
String sql_insrt ="INSERT INTO cadastro_cliente(cadastro_nome, cadastro_endereco, cadastro_cep, cadastro_n, cadastro_tel, cadastro_estado, cadastro_rg, cadastro_cpf, cadastro_data,  cadastro_dataReg, cadastro_bairro, cadastro_cidade, cadastro_celu, estado_civil, residencia, email, site, `foto`, sexo) values ('"+nome.getText()+"','"+endereco.getText()+"','"+cep.getText()+"','"+numero.getText()+"','"+telefone.getText()+"','"+uf.getSelectedItem()+"','"+rg.getText()+"','"+cpf.getText()+"','"+nascimento.getText()+"','"+registro.getText()+"','"+bairro.getText()+"','"+cidade.getText()+"','"+celular.getText()+"','"+estadocivil.getSelectedItem()+"','"+residencia.getSelectedItem()+"','"+email.getText()+"','"+site.getText()+"','"+Fotu.getText()+"','"+sexualidade+"')";
software_sokkyo.statement.executeUpdate(sql_insrt);
JOptionPane.showMessageDialog(null,"Cliente Cadastrado Com Sucesso!");
software_sokkyo.executeSQL("select * from cadastro_cliente");
calcularNumero();
PreencherTable();
software_sokkyo.resultset.last();
mostrar_dados();
 navega = 2;
}

 catch(SQLException erros){
     JOptionPane.showMessageDialog(null,"Erro Ao Gravar Dados! Por Favor Digite Novamente!  "+erros);
  }
   }
 else
       JOptionPane.showMessageDialog(null,"Digite um Email Valido!");
   return;
  

}
        }
     
if(jTabbedPane1.getSelectedIndex() == (2)){
    if(VerificarVeiculo().equals("No")){
    try {
  software_sokkyo.executeSQL("select * from veiculos");
String sql_insrt ="INSERT INTO veiculos(marca, modelo, cliente, anoFab, anoMod, placa, km, vistoria, foto,  estado, portas, combustivel, chassi) values ('"+marca.getText()+"','"+modelo.getText()+"','"+clienteV.getText()+"','"+anoFab.getText()+"','"+anoMod1.getText()+"','"+placaC.getText()+"','"+km.getText()+"','"+vistoria.getText()+"','"+fc.getText()+"','"+jComboBox9.getSelectedItem()+"','"+jComboBox8.getSelectedItem()+"','"+jComboBox10.getSelectedItem()+"','"+chassi.getText()+"')";
software_sokkyo.statement.executeUpdate(sql_insrt);
JOptionPane.showMessageDialog(null,"Carro Cadastrado Com Sucesso!");
PreencherTable2();


}

 catch(SQLException erros){
     JOptionPane.showMessageDialog(null,"Erro ao gravar dados!");
  }
    }
 }
 


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
   if(jTabbedPane1.getSelectedIndex() == (0)){
    if(Verificar().equals("No")){
       try{
 String sql = "UPDATE softwaresokkyo.cadastro_cliente SET `cadastro_nome` = '"+nome.getText()+"', `cadastro_endereco` = '"+endereco.getText()+"', `cadastro_cep` = '"+cep.getText()+"', `cadastro_n` = '"+numero.getText()+"', `cadastro_tel` = '"+telefone.getText()+"', `cadastro_estado` = '"+uf.getSelectedItem()+"', `cadastro_rg` = '"+rg.getText()+"', `cadastro_cpf` = '"+cpf.getText()+"', `cadastro_data` = '"+nascimento.getText()+"', `cadastro_dataReg` = '"+registro.getText()+"', `cadastro_bairro` = '"+bairro.getText()+"', `cadastro_cidade` = '"+cidade.getText()+"', `cadastro_celu` = '"+celular.getText()+"', `estado_civil` = '"+estadocivil.getSelectedItem()+"', `residencia` = '"+residencia.getSelectedItem()+"', `email` = '"+email.getText()+"', `site` = '"+site.getText()+"', `foto` = '"+Fotu.getText()+"', `sexo` = '"+sexualidade+"' WHERE codigo_cliente = "+codigo1.getText();
 software_sokkyo.statement.executeUpdate(sql);
 JOptionPane.showMessageDialog(null,"Alteraçao do cliente realizada com sucesso!");
  software_sokkyo.executeSQL("select * from cadastro_cliente");
 PreencherTable();
 software_sokkyo.resultset.first();
 mostrar_dados();
 navega = 1;


}

catch (SQLException erro)
{
JOptionPane.showMessageDialog(null,"Erro a Tentar Alterar o registro.."+erro);
        }
       }
        }
if(jTabbedPane1.getSelectedIndex() == (2)){
      if(VerificarVeiculo().equals("No")){
  try{
    String sql = "UPDATE softwaresokkyo.veiculos SET `marca` = '"+marca.getText()+"', `modelo` = '"+modelo.getText()+"', `cliente` = '"+clienteV.getText()+"', `anoFab` = '"+anoFab.getText()+"', `anoMod` = '"+anoMod1.getText()+"', `placa` = '"+placaC.getText()+"', `km` = '"+km.getText()+"', `vistoria` = '"+vistoria.getText()+"', `foto` = '"+fc.getText()+"', `estado` = '"+jComboBox9.getSelectedItem()+"', `portas` = '"+jComboBox8.getSelectedItem()+"', `combustivel` = '"+jComboBox10.getSelectedItem()+"', `chassi` = '"+chassi.getText()+"' WHERE idveiculos = "+codigo.getText();
 software_sokkyo.statement.executeUpdate(sql);
JOptionPane.showMessageDialog(null,"Alteraçao do carro realizada com sucesso!");
PreencherTable2();
 software_sokkyo.executeSQL("Select * from cadastro_cliente");



}

catch (SQLException erro)
{
JOptionPane.showMessageDialog(null,"Erro a tentar alterar o registro..");
        }
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
  if(jTabbedPane1.getSelectedIndex() == (0)){
      
  try{
        String sql ="select * FROM softwaresokkyo.cadastro_cliente WHERE `codigo_cliente` = "+codigo1.getText();
software_sokkyo.executeSQL(sql);
software_sokkyo.resultset.first();
String nome = "Tem Certeza Deseja Excluir o Cliente:  "+software_sokkyo.resultset.getString("cadastro_nome")+" ?";
int opcao_escolhida = JOptionPane.showConfirmDialog(null,nome," Exclusão",JOptionPane.YES_NO_OPTION);

if ( opcao_escolhida == JOptionPane.YES_OPTION){

sql = "DELETE FROM softwaresokkyo.cadastro_cliente WHERE `codigo_cliente` = "+codigo1.getText();
int conseguiu_excluir = software_sokkyo.statement.executeUpdate(sql);
if (conseguiu_excluir == 1){

JOptionPane.showMessageDialog(null,"Exclusão do cliente realizada com sucesso! ");
software_sokkyo.executeSQL("select * from cadastro_cliente");
calcularNumero();
 PreencherTable();
 software_sokkyo.resultset.first();
 mostrar_dados();
 navega = 1;

}
}

else{
 return;
    }
  }
catch (SQLException erro)
{
JOptionPane.showMessageDialog(null,"Erro ao excluir o registro");
}
        }
if(jTabbedPane1.getSelectedIndex() == (2)){
     try{
        String sql ="select * FROM softwaresokkyo.veiculos WHERE `idveiculos` = "+codigo.getText();
software_sokkyo.executeSQL(sql);
software_sokkyo.resultset.first();
String nome2 = "Tem Certeza Deseja Excluir o Cliente:  "+software_sokkyo.resultset.getString("marca")+" ?";
int opcao_escolhida = JOptionPane.showConfirmDialog(null,nome2," Exclusão",JOptionPane.YES_NO_OPTION);

if ( opcao_escolhida == JOptionPane.YES_OPTION){

sql = "DELETE FROM softwaresokkyo.veiculos WHERE `idveiculos` = "+codigo.getText();
int conseguiu_excluir = software_sokkyo.statement.executeUpdate(sql);
if (conseguiu_excluir == 1){

JOptionPane.showMessageDialog(null,"Exclusão do carro realizada com sucesso! ");
PreencherTable2();


}
}

else{
 return;
    }
  }
catch (SQLException erro)
{
JOptionPane.showMessageDialog(null,"Erro ao excluir o registro");
}
 }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
    try{
    JFileChooser buscar_fotos = new JFileChooser();
    buscar_fotos.setCurrentDirectory(new File(""));
   buscar_fotos.setDialogTitle("Carregar imagen do carro");
    buscar_fotos.showOpenDialog(this);
    String fotos = "";
     fotos = ""+buscar_fotos.getSelectedFile();
     fotos = fotos.replaceAll("\\\\", "/");
      fc.setText(fotos);
    foto.setIcon(new ImageIcon(""+fc.getText()));

}
  catch(Exception erro){
  }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
if(jTabbedPane1.getSelectedIndex() == (0)){

 BuscaNome.setText("");
buscaCPF.setText("");
nome.setText("");
codigo1.setText("");
endereco.setText("");
cep.setText("");
bairro.setText("");
numero.setText("");
cidade.setText("");
 telefone.setText("");
 celular.setText("");
 rg.setText("");
 cpf.setText("");
 nascimento.setText("");
 email.setText("");
 site.setText("");
 fotux.setIcon( new javax.swing.ImageIcon(getClass().getResource("/icones/people(3).png")));
registro.setText(""+data.getDate()+"/"+(data.getMonth()+1)+"/"+(data.getYear()+1900));

        }
if(jTabbedPane1.getSelectedIndex() == (2)){
     placa.setText("");
     marca.setText("");
     codigo.setText("");
     chassi.setText("");
     modelo.setText("");
     clienteV.setText("");
     anoFab.setText("");
     anoMod1.setText("");
     placaC.setText("");
     km.setText("");
     vistoria.setText("");
     foto.setIcon( new javax.swing.ImageIcon(getClass().getResource("/icones/carros+financiamos+e+aprovamos+cadastro__3BB043_1 - Cópia.jpg")));
 }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        new Consulta_Cliente().show();
        dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void BuscaNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscaNomeActionPerformed
     software_sokkyo.executeSQL("select * from cadastro_cliente");
        if (BuscaNome.getText().equals("")){
    JOptionPane.showMessageDialog(null,"Por Favor Digite o Nome Do Cliente Desejado!");
return;
}
else



        try	{

software_sokkyo.resultset.first();

String igual ="n";

int tamanho_pesquisa = BuscaNome.getText().length();

while ( igual == "n")
{

String pesquisando = software_sokkyo.resultset.getString("cadastro_nome").substring(0,(tamanho_pesquisa));

if(pesquisando.equals(BuscaNome.getText()))

{
igual = "s";
}

else

software_sokkyo.resultset.next();

}


	codigo1.setText(software_sokkyo.resultset.getString("codigo_cliente"));
	mostrar_dados();
        


}
	catch(SQLException erro)
{
JOptionPane.showMessageDialog(null,"Nao Foi Localizado os Dados ! \nDica: Caso Seja Um Usuario Nao Cadastrado Efetue Um novo Cadastro");
}
    }//GEN-LAST:event_BuscaNomeActionPerformed

    private void buscaCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaCPFActionPerformed
   software_sokkyo.executeSQL("select * from cadastro_cliente");
        if (buscaCPF.getText().equals("")){
    JOptionPane.showMessageDialog(null,"Por Favor Digite o RG Do Cliente Desejado!");
return;
}
else



        try	{

software_sokkyo.resultset.first();

String igual ="n";

int tamanho_pesquisa = buscaCPF.getText().length();

while ( igual == "n")
{

String pesquisando = software_sokkyo.resultset.getString("cadastro_rg").substring(0,(tamanho_pesquisa));

if(pesquisando.equals(buscaCPF.getText()))

{
igual = "s";
}

else

software_sokkyo.resultset.next();

}


	codigo1.setText(software_sokkyo.resultset.getString("codigo_cliente"));
	mostrar_dados();



}
	catch(SQLException erro)
{
JOptionPane.showMessageDialog(null,"Nao foi localizado os dados ! \nDica: Caso Seja Um Usuario Nao Cadastrado Efetue Um novo Cadastro");
}
    }//GEN-LAST:event_buscaCPFActionPerformed

    private void placaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placaActionPerformed
    software_sokkyo.executeSQL("select * from veiculos");
        if (placa.getText().equals("")){
    JOptionPane.showMessageDialog(null,"Por favor digite a placa do carro desejado!");
return;
}
else



        try	{

software_sokkyo.resultset.first();
String igual ="n";

int tamanho_pesquisa = placa.getText().length();

while ( igual == "n")
{

String pesquisando = software_sokkyo.resultset.getString("placa").substring(0,(tamanho_pesquisa));

if(pesquisando.equals(placa.getText()))

{
igual = "s";
}

else

software_sokkyo.resultset.next();

}


      codigo.setText(software_sokkyo.resultset.getString("idveiculos"));
      mostrarDados2();
      software_sokkyo.executeSQL("select * from cadastro_cliente");
      software_sokkyo.resultset.first();
      navega = 1;


}
	catch(SQLException erro)
{
JOptionPane.showMessageDialog(null,"Nao Foi Localizado os Dados do Carro !"+erro);
}
    }//GEN-LAST:event_placaActionPerformed

    private void WWWMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WWWMouseClicked
        try {
            Runtime.getRuntime().exec("cmd.exe /C start iexplore.exe www.nokys.com.br");
        } catch (IOException ex) {
            Logger.getLogger(Cadastro_de_Clientes.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_WWWMouseClicked

    private void WWWMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WWWMouseEntered
        WWW.setForeground(new java.awt.Color(0, 153, 255));
}//GEN-LAST:event_WWWMouseEntered

    private void WWWMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WWWMouseExited
        WWW.setForeground(new java.awt.Color(102, 102, 102));
}//GEN-LAST:event_WWWMouseExited

    private void Ultimo1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ultimo1MouseEntered
       
}//GEN-LAST:event_Ultimo1MouseEntered

    private void Ultimo1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ultimo1MouseExited

}//GEN-LAST:event_Ultimo1MouseExited

    private void Ultimo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ultimo1ActionPerformed
          try
{
   software_sokkyo.resultset.last();
   mostrar_dados();
  navega = 2;

}
catch(SQLException erro)
{
           
}
}//GEN-LAST:event_Ultimo1ActionPerformed

    private void Proximo1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Proximo1MouseEntered

}//GEN-LAST:event_Proximo1MouseEntered

    private void Proximo1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Proximo1MouseExited

}//GEN-LAST:event_Proximo1MouseExited

    private void Proximo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Proximo1ActionPerformed
     try{
     software_sokkyo.resultset.next();
     mostrar_dados();
     navega =2;

            }
  catch(SQLException erro)
  {
             

  }
}//GEN-LAST:event_Proximo1ActionPerformed

    private void Anterior1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Anterior1MouseEntered

}//GEN-LAST:event_Anterior1MouseEntered

    private void Anterior1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Anterior1MouseExited

}//GEN-LAST:event_Anterior1MouseExited

    private void Anterior1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Anterior1ActionPerformed
     try{
                software_sokkyo.resultset.previous();
               mostrar_dados();
               navega =1;
               
            }
 catch(SQLException erro)
 {
            
 }
}//GEN-LAST:event_Anterior1ActionPerformed

    private void Primeiro1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Primeiro1MouseEntered
     
}//GEN-LAST:event_Primeiro1MouseEntered

    private void Primeiro1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Primeiro1MouseExited

}//GEN-LAST:event_Primeiro1MouseExited

    private void Primeiro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Primeiro1ActionPerformed
        try{
           software_sokkyo.resultset.first();
            mostrar_dados();
            navega =1;

          
  
        } catch(SQLException erro){

        }
}//GEN-LAST:event_Primeiro1ActionPerformed

    private void femininoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_femininoItemStateChanged
sexualidade = "Feminino";
    }//GEN-LAST:event_femininoItemStateChanged

    private void masculinoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_masculinoItemStateChanged
sexualidade = "Masculino";
    }//GEN-LAST:event_masculinoItemStateChanged

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
     if(site.getText().equals("")){
         JOptionPane.showMessageDialog(null,"Digite o Site do Cliente");
         return;
     }
 else{
        try {
            Runtime.getRuntime().exec("cmd.exe /C start iexplore.exe "+site.getText());
        } catch (IOException ex) {
            Logger.getLogger(Cadastro_de_Clientes.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        Visualizao("codigo_cliente");
}//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        Visualizao("cadastro_nome");
}//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
BuscarVeiculoFirst();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jPanel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel11MouseClicked

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        try {
            geraRelatorio();
        } catch (JRException ex) {
            Logger.getLogger(Cadastro_de_Clientes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Cadastro_de_Clientes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Cadastro_de_Clientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
     dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

     public void geraRelatorio() throws JRException, SQLException, ClassNotFoundException {  
         HashMap map = new HashMap();  
         String arquivo = "F:\\Noky's System\\Software Sokkyo\\src\\com\\Sokkyo\\Cadastros\\report2.jasper";  
         JasperReport jasperReport = (JasperReport) JRLoader.loadObject(arquivo);  
           
         JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, map,software_sokkyo.getConnection());  
           
         JasperViewer jrviewer = new JasperViewer(jasperPrint, false);  
         jrviewer.setVisible(true);  
     }
     
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
                new Cadastro_de_Clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Anterior1;
    private javax.swing.JTextField BuscaNome;
    private javax.swing.JLabel Fotu;
    private javax.swing.JButton Primeiro1;
    private javax.swing.JButton Proximo1;
    private javax.swing.JButton Ultimo1;
    private javax.swing.JLabel WWW;
    private javax.swing.JTextField anoFab;
    private javax.swing.JTextField anoMod1;
    private javax.swing.JTextField bairro;
    private javax.swing.JFormattedTextField buscaCPF;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JFormattedTextField celular;
    private javax.swing.JFormattedTextField cep;
    private javax.swing.JTextField chassi;
    private javax.swing.JTextField cidade;
    private javax.swing.JTextField clienteV;
    private javax.swing.JTextField codigo;
    private javax.swing.JTextField codigo1;
    private javax.swing.JFormattedTextField cpf;
    private javax.swing.JTextField email;
    private javax.swing.JTextField endereco;
    private javax.swing.JComboBox estadocivil;
    private javax.swing.JLabel fc;
    private javax.swing.JRadioButton feminino;
    private javax.swing.JLabel foto;
    private javax.swing.JLabel fotux;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox10;
    private javax.swing.JComboBox jComboBox8;
    private javax.swing.JComboBox jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField km;
    private javax.swing.JTextField marca;
    private javax.swing.JRadioButton masculino;
    private javax.swing.JTextField modelo;
    private javax.swing.JFormattedTextField nascimento;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField numero;
    private javax.swing.JLabel numerodecliente;
    private javax.swing.JLabel numerodecliente1;
    private javax.swing.JTextField placa;
    private javax.swing.JTextField placaC;
    private javax.swing.JTextField registro;
    private javax.swing.JComboBox residencia;
    private javax.swing.JFormattedTextField rg;
    private javax.swing.ButtonGroup sexo;
    private javax.swing.JTextField site;
    private javax.swing.JFormattedTextField telefone;
    private javax.swing.JComboBox uf;
    private javax.swing.JFormattedTextField vistoria;
    // End of variables declaration//GEN-END:variables
 public void mostrar_dados() throws SQLException{
   try{
     codigo1.setText(software_sokkyo.resultset.getString("codigo_cliente"));
nome.setText(software_sokkyo.resultset.getString("cadastro_nome"));
endereco.setText(software_sokkyo.resultset.getString("cadastro_endereco"));
cep.setText(software_sokkyo.resultset.getString("cadastro_cep"));
bairro.setText(software_sokkyo.resultset.getString("cadastro_bairro"));
numero.setText(software_sokkyo.resultset.getString("cadastro_n"));
cidade.setText(software_sokkyo.resultset.getString("cadastro_cidade"));
 telefone.setText(software_sokkyo.resultset.getString("cadastro_tel"));
 celular.setText(software_sokkyo.resultset.getString("cadastro_celu"));
 rg.setText(software_sokkyo.resultset.getString("cadastro_rg"));
 cpf.setText(software_sokkyo.resultset.getString("cadastro_cpf"));
 nascimento.setText(software_sokkyo.resultset.getString("cadastro_data"));
 email.setText(software_sokkyo.resultset.getString("email"));
 site.setText(software_sokkyo.resultset.getString("site"));
 uf.setSelectedItem(software_sokkyo.resultset.getString("cadastro_estado"));
 estadocivil.setSelectedItem(software_sokkyo.resultset.getString("estado_civil"));
 residencia.setSelectedItem(software_sokkyo.resultset.getString("residencia"));
 registro.setText(software_sokkyo.resultset.getString("cadastro_dataReg"));
fotux.setIcon(new ImageIcon(""+software_sokkyo.resultset.getString("foto")));
Fotu.setText(software_sokkyo.resultset.getString("foto"));
sexualidade= software_sokkyo.resultset.getString("sexo");
clienteV.setText(nome.getText());
if ( sexualidade.equals("Feminino")){
    feminino.setSelected(rootPaneCheckingEnabled);
}
 else {
    masculino.setSelected(rootPaneCheckingEnabled);
 }
   }

 catch(SQLException erro){
 if (navega == 1){
                    JOptionPane.showMessageDialog(null, "Voçê jà Está no Primeiro Registro.");
                    software_sokkyo.resultset.next();
                  }
                else if(navega == 2){
                    JOptionPane.showMessageDialog(null, "Voçê jà Está no Ultimo Registro.");
                     software_sokkyo.resultset.previous();
                  }
                else
             
              navega = 0;

 }}



  public void PreencherTable(){

    DefaultTableModel mo = (DefaultTableModel)jTable1.getModel();
    mo.setNumRows(0);
    try{
        while (software_sokkyo.resultset.next())
            mo.addRow(new Object[]{software_sokkyo.resultset.getString("codigo_cliente"),software_sokkyo.resultset.getString("cadastro_nome"),software_sokkyo.resultset.getString("cadastro_tel"),software_sokkyo.resultset.getString("cadastro_rg"),software_sokkyo.resultset.getString("cadastro_cpf")});

        }
    catch (SQLException erro){
        JOptionPane.showMessageDialog(null,"Erro Ao Aprensentar Dados na Tabela");
    }

}
  public void Limpar(){
       placa.setText("");
     marca.setText("");
     codigo.setText("");
     chassi.setText("");
     modelo.setText("");
     clienteV.setText("");
     anoFab.setText("");
     anoMod1.setText("");
     placaC.setText("");
     km.setText("");
     vistoria.setText("");
     foto.setIcon( new javax.swing.ImageIcon(getClass().getResource("/icones/carros+financiamos+e+aprovamos+cadastro__3BB043_1 - Cópia.jpg")));
  }
public void mostrarDados2(){
        
    try{
     codigo.setText(software_sokkyo.resultset.getString("idveiculos"));
marca.setText(software_sokkyo.resultset.getString("marca"));
modelo.setText(software_sokkyo.resultset.getString("modelo"));
clienteV.setText(software_sokkyo.resultset.getString("cliente"));
anoFab.setText(software_sokkyo.resultset.getString("anoFab"));
anoMod1.setText(software_sokkyo.resultset.getString("anoMod"));
placaC.setText(software_sokkyo.resultset.getString("placa"));
 km.setText(software_sokkyo.resultset.getString("km"));
 vistoria.setText(software_sokkyo.resultset.getString("vistoria"));
 jComboBox9.setSelectedItem(software_sokkyo.resultset.getString("estado"));
jComboBox8.setSelectedItem(software_sokkyo.resultset.getString("portas"));
jComboBox10.setSelectedItem(software_sokkyo.resultset.getString("combustivel"));
 chassi.setText(software_sokkyo.resultset.getString("chassi"));
  foto.setIcon(new ImageIcon(""+software_sokkyo.resultset.getString("foto")));
    }
 catch(SQLException erro){
      JOptionPane.showMessageDialog(null,"Nao localizou dados do veiculo! "+erro);
}

}

public String Verificar(){
    String yes;
    if (nome.getText().equals("") || endereco.equals("") || bairro.equals("") || numero.equals("") || cidade.equals("") || sexualidade.equals("") ){
        JOptionPane.showMessageDialog(null,"Por Favor digite os dados do cliente !");
      yes  = "Yes";
 return yes;


    }
     else{
         yes = "No";
  return yes;
    }

}
 public void Visualizao(String ordem){
     ordenaçao = ordem;
     software_sokkyo.executeSQL("select * from cadastro_cliente order by "+ordenaçao);
     PreencherTable();
        try {

 software_sokkyo.executeSQL("select * from cadastro_cliente");
 software_sokkyo.resultset.first();
 mostrar_dados();
 navega = 1;

        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null,"Nao Foi Possivel alterar a ordenação!");
        }


 }
public String VerificarVeiculo(){
    String veri;
    if(marca.getText().equals("") || chassi.equals("") || modelo.equals("") || placaC.equals("") || clienteV.equals("")){
        JOptionPane.showMessageDialog(null,"Digite os dados do Veiculo");
       veri = "Yes";
        return  veri;
    }

 else {
        veri = "No";
        return veri;
 }
}
public void PreencherTable2(){
software_sokkyo.executeSQL("select * from veiculos");
    DefaultTableModel mode = (DefaultTableModel)jTable2.getModel();
    mode.setNumRows(0);
    try{
        while (software_sokkyo.resultset.next())
            mode.addRow(new Object[]{software_sokkyo.resultset.getString("modelo"),software_sokkyo.resultset.getString("placa"),software_sokkyo.resultset.getString("marca"),software_sokkyo.resultset.getString("chassi"),software_sokkyo.resultset.getString("cliente")});

        }
    catch (SQLException erro){
        JOptionPane.showMessageDialog(null,"Erro Ao Aprensentar Dados na Tabela");
    }

}

public String validate(String arg) {
    String resposta = "Valido";
        if ((arg.length() < 4) || !arg.contains("@") || !arg.contains(".")) {
            return resposta = "Invalido";
        }
        return resposta;
    }

 public void calcularNumero() throws SQLException{
software_sokkyo.resultset.first();
 int i = 1;
     while(software_sokkyo.resultset.next()){
       i++;

  }
   numerodecliente.setText(""+i);
   software_sokkyo.executeSQL("select * from cadastro_cliente");
 }

public void BuscarVeiculoFirst(){
    software_sokkyo.executeSQL("select * from veiculos");
        if (clienteV.getText().equals("")){
    JOptionPane.showMessageDialog(null,"Por favor digite o cliente!");
return;
}else

        try	{

software_sokkyo.resultset.first();
String igual = "n";


while ( igual == "n")
{

String pesquisando = software_sokkyo.resultset.getString("cliente");

if(pesquisando.equals(clienteV.getText()))

{
igual = "s";
}

else

software_sokkyo.resultset.next();

}


	codigo.setText(software_sokkyo.resultset.getString("idveiculos"));
        mostrarDados2();
      software_sokkyo.executeSQL("select * from cadastro_cliente");
      software_sokkyo.resultset.first();
       navega = 1;


}
	catch(SQLException erro){
JOptionPane.showMessageDialog(null,"Nao Foi Localizado o Carro !");
 software_sokkyo.executeSQL("select * from cadastro_cliente");
   try{
 software_sokkyo.resultset.first();
     navega = 1;
    }
   catch(Exception e )
    {

   }
            }
            }




}
