import java.lang.reflect.Array;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
/*
 * FCadServidor.java
 *
 * Created on 29 de Novembro de 2005, 14:44
 */

/**
 *
 * @author  rodrigo.tavares
 */
public class FCadServidor extends javax.swing.JFrame {
    
    /** Creates new form FCadServidor */
    public FCadServidor() {
        initComponents();
        setBounds(100,100,410,250); 
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        CBSetor = new javax.swing.JComboBox();
        CBFuncao = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        getContentPane().setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciador de Di\u00e1rias ASTEC-PB v1.0");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.setFont(new java.awt.Font("MS Sans Serif", 1, 12));
        jLabel1.setText("Cadastro de Servidor");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(110, 10, 150, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 380, 40);

        jPanel2.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel2.setText("Nome:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 10, 50, 15);

        jLabel3.setText("Setor:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 60, 50, 15);

        jPanel2.add(txtNome);
        txtNome.setBounds(10, 30, 360, 20);

        jPanel2.add(CBSetor);
        CBSetor.setBounds(10, 80, 150, 19);

        jPanel2.add(CBFuncao);
        CBFuncao.setBounds(180, 80, 190, 19);

        jLabel4.setText("Fun\u00e7\u00e3o:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(180, 60, 50, 15);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 60, 380, 110);

        jPanel3.setLayout(null);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        jPanel3.add(btnSalvar);
        btnSalvar.setBounds(100, 10, 90, 23);

        btnCancelar.setText("Cancelar");
        jPanel3.add(btnCancelar);
        btnCancelar.setBounds(190, 10, 90, 23);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(10, 180, 380, 40);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
// TODO add your handling code here:   
        if(txtNome.getText().trim().length() == 0){
         JOptionPane.showMessageDialog(null,"Preencha os campos","ATENÇÃO",JOptionPane.WARNING_MESSAGE);
         }else{
        ClassServidor servidor = new ClassServidor();
        servidor.setServidor(txtNome.getText(), CBSetor.getSelectedItem().toString(), CBFuncao.getSelectedItem().toString());
        servidor.incluiServidor();
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
// TODO add your handling code here:

       ClassConecta conexao = new ClassConecta();
        try{
          Connection  con = conexao.conecta();
          Statement stmt= con.createStatement();          
          ResultSet rsSetor = stmt.executeQuery("select * from TabCadSetor");//Pega os valores da tabela CadSetor
          
          while(rsSetor.next()){ // Faz o loop para preencher o ComboSetor          
            String setor = rsSetor.getString(2);
            CBSetor.addItem(setor);              
          } 
        rsSetor.close();
        /*
         * OBS:
         * Para poder preencher os 2 combobox(setor e funcao) 
         * tive que primeiro preencher um e fechar o resultset de setor(rsSetor)
         * para depois poder preencher o outro.
         * se não fizesse isto ele não preenchia nenhum dos 
         *combobox
         */
        ResultSet rsFuncao = stmt.executeQuery("select * from TabFuncao");
        while(rsFuncao.next()){//loop para preencher o combobox de funcao
               String funcao = rsFuncao.getString(2);
               CBFuncao.addItem(funcao);
              }
        
         rsFuncao.close();
         stmt.close();// fecho o stetement
        }catch(SQLException e){
          JOptionPane.showMessageDialog(null,"Ocorreu um erro no sistema, se persistir contate o Administrador '"+ e +"","ATENÇÃO",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_formWindowOpened
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FCadServidor().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CBFuncao;
    private javax.swing.JComboBox CBSetor;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
    
}
