import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/*
 * FConsultServidor.java
 *
 * Created on 6 de Dezembro de 2005, 14:08
 */

/**
 *
 * @author  rodrigo.tavares
 */
public class FConsultServidor extends javax.swing.JFrame {
    
    /** Creates new form FConsultServidor */
    public FConsultServidor() {
        initComponents();
        setBounds(200,100,570,330);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        CBSetor = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        CBSituacao = new javax.swing.JComboBox();
        btnLocaliza = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnEntregaRel = new javax.swing.JButton();
        btncancelaDiaria = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();

        getContentPane().setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciador de Di\u00e1rias ASTEC-PB v1.0");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.setFont(new java.awt.Font("MS Sans Serif", 1, 18));
        jLabel1.setText("Localizar Servidor");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(190, 10, 250, 15);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 540, 40);

        jPanel2.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Saída", "Chegada", "Destino", "Relatório"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabela);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 520, 80);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 60, 540, 100);

        jPanel3.setLayout(null);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel2.setText("Nome:");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(10, 10, 60, 15);

        jLabel3.setText("Setor:");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(270, 10, 50, 15);

        txtNome.setToolTipText("Informe o Nome do Servidor Exatamente como voc\u00ea o salvou Ex.\" Rodrigo Fl\u00e1vio de Oliveira Tavares\"");
        jPanel3.add(txtNome);
        txtNome.setBounds(10, 30, 250, 20);

        jPanel3.add(CBSetor);
        CBSetor.setBounds(270, 30, 110, 19);

        jLabel4.setText("Situa\u00e7\u00e3o:");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(390, 10, 70, 15);

        CBSituacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DEVENDO", "ENTREGUE", "CANCELADA" }));
        jPanel3.add(CBSituacao);
        CBSituacao.setBounds(390, 30, 100, 19);

        btnLocaliza.setIcon(new javax.swing.ImageIcon("C:\\Documents and Settings\\rodrigo.tavares\\Meus documentos\\Projeto Funasa\\Diaria\\diaria\\Figuras\\Localizar.gif"));
        btnLocaliza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocalizaActionPerformed(evt);
            }
        });

        jPanel3.add(btnLocaliza);
        btnLocaliza.setBounds(500, 20, 30, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(10, 170, 540, 60);

        jPanel4.setLayout(null);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnEntregaRel.setText("Entregar Relat\u00f3rio");
        btnEntregaRel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntregaRelActionPerformed(evt);
            }
        });

        jPanel4.add(btnEntregaRel);
        btnEntregaRel.setBounds(40, 10, 150, 23);

        btncancelaDiaria.setText("Cancelar Di\u00e1ria");
        btncancelaDiaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelaDiariaActionPerformed(evt);
            }
        });

        jPanel4.add(btncancelaDiaria);
        btncancelaDiaria.setBounds(200, 10, 150, 23);

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        jPanel4.add(btnSair);
        btnSair.setBounds(360, 10, 150, 23);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(10, 240, 540, 40);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents

    private void btncancelaDiariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelaDiariaActionPerformed
// TODO add your handling code here:
  //Váriaveis para pegar o valor da linha selecionada
          int linha = tabela.getSelectedRow();
          int coluna = tabela.getSelectedColumn(); 
          if(linha == -1){//para saber se existe uma linha selecionada
           JOptionPane.showMessageDialog(null,"Selecione uma linha","ATENÇÃO",JOptionPane.WARNING_MESSAGE);
          }else{
          //Variáveis para pegar os valores das colunas da jTable
          String codigo = ((DefaultTableModel)tabela.getModel()).getValueAt(linha,0).toString();
          String nome = ((DefaultTableModel)tabela.getModel()).getValueAt(linha,1).toString();
          String dataSaida = ((DefaultTableModel)tabela.getModel()).getValueAt(linha,2).toString();
          String dataChegada = ((DefaultTableModel)tabela.getModel()).getValueAt(linha,3).toString();
          String destino = ((DefaultTableModel)tabela.getModel()).getValueAt(linha,4).toString();    
          String situacao = ((DefaultTableModel)tabela.getModel()).getValueAt(linha,5).toString();
       int  pegaCod = Integer.parseInt(codigo);  
        if(situacao.trim().equals("CANCELADA")){
           JOptionPane.showMessageDialog(null,"Diária já Cancelada","ATENÇÃO",JOptionPane.WARNING_MESSAGE);
        }else{
          ClassDiaria diaria = new ClassDiaria();          
          diaria.setCodigo(pegaCod);          
          diaria.setDeletaDiaria(nome, dataSaida, dataChegada, destino);
          diaria.DeletaDiaria();
        }
      }
    }//GEN-LAST:event_btncancelaDiariaActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
// TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnLocalizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocalizaActionPerformed
// TODO add your handling code here:
      if(txtNome.getText().trim().length() == 0){
       JOptionPane.showMessageDialog(null,"Preencha o Campo Nome Corretamente","ATENÇÃO",JOptionPane.WARNING_MESSAGE);
      }else{  
      int  linha = tabela.getRowCount();
      int i =0;  
     if(i < linha){
     while(i <= linha){
         ((DefaultTableModel)tabela.getModel()).removeRow(0);
         i++;
       }
     }else{
   try{   
         String nome = txtNome.getText();
         String setor = CBSetor.getSelectedItem().toString();
         String situacao =  CBSituacao.getSelectedItem().toString();
         ClassDiaria diaria = new ClassDiaria();
         ClassConecta conexao = new ClassConecta();
         Connection con = conexao.conecta();
         Statement stmt = conexao.con.createStatement();        
         ResultSet rs = stmt.executeQuery("Select * from TabCadDiaria where nome like '" + nome + "%' and setor= '" + setor + "' and situacao ='" + situacao + "'");
        //System.out.println(nome +  "-" + setor + " - " + situacao );
         while(rs.next()){     
            // System.out.println(rs.getString("nome"));
              //Adicionando os Dados da tabela na jTable              
            ((DefaultTableModel)tabela.getModel()).addRow(new Object[] {rs.getObject(1),
              rs.getObject(2),rs.getObject(3), rs.getObject(4), rs.getObject(5),rs.getObject(6)});                         
            }
         
         //para os botões não ficarem ativos
         if(CBSituacao.getSelectedIndex() == 0){ //Devendo
            btncancelaDiaria.setEnabled(true);
            btnEntregaRel.setEnabled(true);             
         }else{
         if(CBSituacao.getSelectedIndex() == 1){ //Entregue            
            btncancelaDiaria.setEnabled(false);
            btnEntregaRel.setEnabled(true);
        }else{
            if(CBSituacao.getSelectedIndex() == 2){  //Cancelada                      
            btnEntregaRel.setEnabled(false);
            btncancelaDiaria.setEnabled(true);  
             }
           }
         }  
         //====================================================
         
         
            if(tabela.getRowCount() == 0 ){
              JOptionPane.showMessageDialog(null,"Nenhum Servidor Encontrado. Você informou o Nome, Setor ou Situação Corretos?","ATENÇÃO",JOptionPane.WARNING_MESSAGE);
              }
       }catch(SQLException e){
          JOptionPane.showMessageDialog(null,"Ocorreu um erro no sistema, se persistir contate o Administrador '"+ e +"","ATENÇÃO",JOptionPane.WARNING_MESSAGE);
       }
     }
  }//do 1 if
    }//GEN-LAST:event_btnLocalizaActionPerformed

    private void btnEntregaRelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntregaRelActionPerformed
// TODO add your handling code here:
          int linha = tabela.getSelectedRow();
          int coluna = tabela.getSelectedColumn(); 
          if(linha == -1){//para saber se existe uma linha selecionada
            JOptionPane.showMessageDialog(null,"Selecione uma linha","ATENÇÃO",JOptionPane.WARNING_MESSAGE);             
          }else{
          //Variável para pegar o valor da coluna da jTable
          String codigo = ((DefaultTableModel)tabela.getModel()).getValueAt(linha,0).toString();
          //converte para número
          int  pegaCod = Integer.parseInt(codigo);
          String Situacao = ((DefaultTableModel)tabela.getModel()).getValueAt(linha,5).toString();
          ClassDiaria diaria = new ClassDiaria();    
          if(Situacao.trim().equals("ENTREGUE")){
            JOptionPane.showMessageDialog(null,"Relatório já entregue","ATENÇÃO",JOptionPane.WARNING_MESSAGE);              
          }else{
          diaria.setCodigo(pegaCod);
          diaria.EntregaRel();
          //Depois de Atualizada a jTable recebe o Valor de Entregue
          ((DefaultTableModel)tabela.getModel()).setValueAt("ENTREGUE", linha,5);
          }
        }  
    }//GEN-LAST:event_btnEntregaRelActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
// TODO add your handling code here:
     try{         
         ClassConecta conexao = new ClassConecta();
         conexao.conecta();
         Statement stmt = conexao.con.createStatement();                        
         ResultSet rsSetor = stmt.executeQuery("select * from TabCadSetor");
          while(rsSetor.next()){
              CBSetor.addItem(rsSetor.getString("nome"));
          }          
          rsSetor.close();
          stmt.close();
         }catch(SQLException e){
           JOptionPane.showMessageDialog(null,"Ocorreu um erro no sistema, se persistir contate o Administrador '"+ e +"","ATENÇÃO",JOptionPane.WARNING_MESSAGE);
        }
            
    }//GEN-LAST:event_formWindowOpened
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FConsultServidor().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CBSetor;
    private javax.swing.JComboBox CBSituacao;
    private javax.swing.JButton btnEntregaRel;
    private javax.swing.JButton btnLocaliza;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btncancelaDiaria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
    
}
