/*
 * FEntregaRelatorio.java
 *
 * Created on 16 de Novembro de 2005, 15:34
 */

/**
 *
 * @author  rodrigo.tavares
 */
public class FEntregaRelatorio extends javax.swing.JFrame {
    
    /** Creates new form FEntregaRelatorio */
    public FEntregaRelatorio() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblDatasaida = new javax.swing.JLabel();
        lblServidor = new javax.swing.JLabel();
        lblDataChegada = new javax.swing.JLabel();
        lblDestino = new javax.swing.JLabel();
        lblSituacao = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        getContentPane().setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("MS Sans Serif", 1, 12));
        jLabel1.setText("Entrega de Relat\u00f3rio");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 10, 150, 16);

        jPanel1.setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel2.setText("Servidor");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 10, 41, 15);

        jLabel4.setText("Data de Sa\u00edda:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 30, 70, 15);

        jLabel5.setText("Data de Chegada:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 50, 86, 15);

        jLabel6.setText("Destino:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 70, 39, 15);

        jLabel3.setText("Situa\u00e7\u00e3o Atual:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 90, 73, 15);

        lblDatasaida.setText("jLabel3");
        jPanel1.add(lblDatasaida);
        lblDatasaida.setBounds(60, 10, 260, 15);

        lblServidor.setText("jLabel3");
        jPanel1.add(lblServidor);
        lblServidor.setBounds(80, 30, 140, 15);

        lblDataChegada.setText("jLabel3");
        jPanel1.add(lblDataChegada);
        lblDataChegada.setBounds(100, 50, 130, 15);

        lblDestino.setText("jLabel3");
        jPanel1.add(lblDestino);
        lblDestino.setBounds(60, 70, 260, 15);

        lblSituacao.setText("jLabel7");
        jPanel1.add(lblSituacao);
        lblSituacao.setBounds(90, 90, 120, 15);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 40, 330, 120);

        jPanel2.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.setText("jButton1");
        jPanel2.add(jButton1);
        jButton1.setBounds(80, 10, 71, 23);

        jButton2.setText("jButton2");
        jPanel2.add(jButton2);
        jButton2.setBounds(170, 10, 71, 23);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 170, 330, 40);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
// TODO add your handling code here:        
        FListaDiarias d = new FListaDiarias();
        
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
// TODO add your handling code here:

    }//GEN-LAST:event_formWindowActivated
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FEntregaRelatorio().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblDataChegada;
    private javax.swing.JLabel lblDatasaida;
    private javax.swing.JLabel lblDestino;
    private javax.swing.JLabel lblServidor;
    private javax.swing.JLabel lblSituacao;
    // End of variables declaration//GEN-END:variables
    
}
