import java.sql.SQLException;
/*
 * FListaSetor.java
 *
 * Created on 16 de Dezembro de 2005, 15:01
 */

/**
 *
 * @author  rodrigo.tavares
 */
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class FListaSetor extends javax.swing.JFrame {
    
    /** Creates new form FListaSetor */
    public FListaSetor() {
        initComponents();
        setBounds(250,250,360,290);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        btnExcluiServidor = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();

        getContentPane().setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciador de Di\u00e1rias ASTEC-PB v1.0");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnExcluiServidor.setText("Excluir Setor");
        btnExcluiServidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluiServidorActionPerformed(evt);
            }
        });

        jPanel1.add(btnExcluiServidor);
        btnExcluiServidor.setBounds(10, 10, 150, 23);

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        jPanel1.add(btnSair);
        btnSair.setBounds(160, 10, 160, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 210, 330, 40);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome"
            }
        ));
        tabela.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(tabela);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 330, 190);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
// TODO add your handling code here:
       this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnExcluiServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluiServidorActionPerformed
// TODO add your handling code here:
          //Váriaveis para pegar o valor da linha selecionada
          int linha = tabela.getSelectedRow();
          int coluna = tabela.getSelectedColumn(); 
        if(linha == -1){      
          JOptionPane.showMessageDialog(null,"Selecione uma linha","ATENÇÃO",JOptionPane.WARNING_MESSAGE);
        }else{
          //Variáveis para pegar os valores das colunas da jTable
          String codigo = ((DefaultTableModel)tabela.getModel()).getValueAt(linha,0).toString();
          String nome = ((DefaultTableModel)tabela.getModel()).getValueAt(linha,1).toString();
         
          int ConvertCodigo = Integer.parseInt(codigo);
          
          ClassCadSetor CSetor = new ClassCadSetor();
          CSetor.setCodigo(ConvertCodigo);
          CSetor.setNome(nome);
          CSetor.deletaSetor();
          ((DefaultTableModel)tabela.getModel()).removeRow(linha);//para remover a linha excluída
          JOptionPane.showMessageDialog(null,"Setor Excluído com Sucesso","ATENÇÃO",JOptionPane.INFORMATION_MESSAGE);
            }
    }//GEN-LAST:event_btnExcluiServidorActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
// TODO add your handling code here:
       Statement stmt= null;
       Connection  con = null;
     try{         
         //ClassDiaria CDiaria = new ClassDiaria();
         ClassConecta conexao = new ClassConecta();
         conexao.conecta();
         stmt = conexao.con.createStatement();
         ResultSet rs = stmt.executeQuery("Select * from TabCadSetor");
         // ==> retorna o número de colunas de uma tabela "rs.getMetaData().getColumnCount();"
         while(rs.next()){     
              //Adicionando os Dados da tabela na jTable              
             ((DefaultTableModel)tabela.getModel()).addRow(new Object[]{rs.getString(1), rs.getString(2)});
            }         
          rs.close();
          stmt.close();
         }catch(SQLException e){
         System.out.println(e);
        } 
        
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
// TODO add your handling code here:
                //Personalizando a largura das Colunas
              tabela.getColumnModel().getColumn(0).setPreferredWidth(70); //Tamanho Inicial
              tabela.getColumnModel().getColumn(0).setMaxWidth(70);//Tamanho Maximo
              tabela.getColumnModel().getColumn(0).setMinWidth(70);//Tamanho Mínimo
              tabela.getColumnModel().getColumn(1).setPreferredWidth(350);
              tabela.getColumnModel().getColumn(1).setMaxWidth(350);
              tabela.getColumnModel().getColumn(1).setMinWidth(350);
         //=============================================================================
    }//GEN-LAST:event_formWindowActivated
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FListaSetor().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluiServidor;
    private javax.swing.JButton btnSair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
    
}
