/*
 * FSobre.java
 *
 * Created on 14 de Dezembro de 2005, 14:48
 */

/**
 *
 * @author  rodrigo.tavares
 */
public class FSobre extends javax.swing.JFrame {
    
    /** Creates new form FSobre */
    public FSobre() {
        initComponents();
        setBounds(250,250,300,220);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();

        getContentPane().setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciador de Di\u00e1rias ASTEC-PB v1.0");
        setResizable(false);
        jLabel1.setFont(new java.awt.Font("MS Sans Serif", 1, 12));
        jLabel1.setText("Desenvolvido Por: ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 10, 130, 16);

        jLabel2.setFont(new java.awt.Font("MS Sans Serif", 1, 12));
        jLabel2.setText("Telefone: 83 - 3235 - 2257 ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 80, 170, 16);

        jLabel3.setFont(new java.awt.Font("MS Sans Serif", 1, 12));
        jLabel3.setText("Celular: 83 - 8824 - 2324");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 100, 160, 16);

        jLabel4.setFont(new java.awt.Font("MS Sans Serif", 1, 12));
        jLabel4.setText("Rodrigo Fl\u00e1vio de Oliveira Tavares");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 40, 210, 16);

        jLabel5.setFont(new java.awt.Font("MS Sans Serif", 1, 12));
        jLabel5.setText("Est\u00e1gi\u00e1rio:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 40, 60, 16);

        jLabel6.setFont(new java.awt.Font("MS Sans Serif", 1, 12));
        jLabel6.setText("Contatos:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 60, 60, 16);

        jLabel7.setFont(new java.awt.Font("MS Sans Serif", 1, 12));
        jLabel7.setText("E-mail: rodrigoflaviotavares@gmail.com");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 120, 240, 16);

        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        getContentPane().add(btnOk);
        btnOk.setBounds(100, 150, 100, 23);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
// TODO add your handling code here:
        this.dispose();        
    }//GEN-LAST:event_btnOkActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FSobre().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
    
}
