/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Venda_ProdServ.java
 *
 * Created on 05/09/2010, 08:24:01
 */

package br.com.sokkyo.view.cadastros;


import javax.swing.JOptionPane;

/**
 *
 * @author Administrador
 */
public class CadastroOrcamento extends javax.swing.JFrame {

double nt0,nt,nt1;
   int navega = 0;
    /** Creates new form Venda_ProdServ */
    public CadastroOrcamento() {
        initComponents();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nome11 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        vscodigocli = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        pnome = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        cod_peca = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        vvalor = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        vqtd = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        vendedor = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        vtotal = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        datae = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        dias = new javax.swing.JComboBox();
        placa = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        vspreço = new javax.swing.JTextField();
        modelo = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        vspreço1 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descrição = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        codigOS = new javax.swing.JTextField();
        BConfirmar = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        Ultimo1 = new javax.swing.JButton();
        Proximo1 = new javax.swing.JButton();
        Anterior1 = new javax.swing.JButton();
        Primeiro1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setTitle("Venda Completa");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(153, 153, 153))); // NOI18N

        nome11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nome11.setNextFocusableComponent(pnome);
        nome11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome11ActionPerformed(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel38.setText("Nome do Cliente");

        vscodigocli.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        vscodigocli.setRequestFocusEnabled(false);

        jLabel41.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel41.setText("Codigo do Cliente");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nome11, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vscodigocli, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nome11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(vscodigocli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 620, 60));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar Peça", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(153, 153, 153))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnome.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pnome.setToolTipText("Digite a Peça e Pressione Enter para Preencher");
        pnome.setMaximumSize(new java.awt.Dimension(20, 6));
        pnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnomeActionPerformed(evt);
            }
        });
        jPanel2.add(pnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 20, 230, 22));

        jLabel43.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel43.setText("Nome da Peça");
        jPanel2.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 20, 88, 20));

        cod_peca.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cod_peca.setFocusable(false);
        cod_peca.setRequestFocusEnabled(false);
        cod_peca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cod_pecaActionPerformed(evt);
            }
        });
        jPanel2.add(cod_peca, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 90, -1));

        jLabel52.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel52.setText("Codigo da Peça");
        jPanel2.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 620, 60));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados do Produto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(153, 153, 153))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        vvalor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        vvalor.setRequestFocusEnabled(false);
        jPanel3.add(vvalor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 90, -1));

        jLabel44.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel44.setText("QTD Dejesada");
        jPanel3.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 90, 20));

        vqtd.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        vqtd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                vqtdFocusLost(evt);
            }
        });
        jPanel3.add(vqtd, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 90, 20));

        jLabel45.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel45.setText("Valor da Peça");
        jPanel3.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 90, 20));

        vendedor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel3.add(vendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 90, 20));

        jLabel54.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel54.setText("Vendedor");
        jPanel3.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 60, 20));

        vtotal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        vtotal.setForeground(new java.awt.Color(255, 0, 0));
        vtotal.setNextFocusableComponent(placa);
        jPanel3.add(vtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 90, 20));

        jLabel48.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(0, 153, 255));
        jLabel48.setText("VALOR");
        jPanel3.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 70, 20));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 620, 80));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados do Orçamento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(153, 153, 153))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        datae.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        datae.setRequestFocusEnabled(false);
        jPanel4.add(datae, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 90, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Data de Entrada");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 100, 20));

        dias.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        dias.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hoje", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "Mais" }));
        jPanel4.add(dias, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 100, -1));

        placa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel4.add(placa, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 90, 20));

        jLabel42.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel42.setText("Modelo");
        jPanel4.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 60, 20));

        vspreço.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        vspreço.setForeground(new java.awt.Color(255, 0, 51));
        vspreço.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                vspreçoFocusLost(evt);
            }
        });
        jPanel4.add(vspreço, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, 100, 20));

        modelo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel4.add(modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 90, 20));

        jLabel49.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel49.setText("Placa do Veiculo");
        jPanel4.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 100, 20));

        jLabel40.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(51, 153, 255));
        jLabel40.setText("VALOR");
        jPanel4.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 70, 20));

        vspreço1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        vspreço1.setForeground(new java.awt.Color(255, 0, 51));
        jPanel4.add(vspreço1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 100, 30));

        jLabel39.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 204, 204));
        jLabel39.setText("TOTAL");
        jPanel4.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 80, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Dias Previsto para Entrega");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 160, 20));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 620, 120));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Descrição", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(153, 153, 153))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        descrição.setColumns(20);
        descrição.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        descrição.setRows(5);
        jScrollPane2.setViewportView(descrição);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 400, 50));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("CODIGO O.S");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 100, 20));

        codigOS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel5.add(codigOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 110, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 620, 110));

        BConfirmar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sokkyo/icones/ok-32x32.png"))); // NOI18N
        BConfirmar.setText("Confirmar");
        BConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(BConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 130, 40));

        jButton14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sokkyo/icones/fechar_32x32.png"))); // NOI18N
        jButton14.setMnemonic('s');
        jButton14.setText(" Sair da Venda");
        jButton14.setToolTipText("Sair do Menu Cadastro");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 150, 40));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sokkyo/Icons/8391_32x32.png"))); // NOI18N
        jButton6.setMnemonic('A');
        jButton6.setText("Adcionar Peça");
        jButton6.setToolTipText("Nova Busca");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 150, 40));

        jButton15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sokkyo/Icons/1588_32x32.png"))); // NOI18N
        jButton15.setMnemonic('N');
        jButton15.setText("Nova Orçamento");
        jButton15.setToolTipText("Novo Cadastro");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jButton15.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jButton15FocusLost(evt);
            }
        });
        getContentPane().add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setText("Nokys Software");
        jLabel11.setToolTipText("");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 90, 20));

        jLabel50.setText("jLabel2");
        getContentPane().add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 10, -1));

        Ultimo1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Ultimo1.setForeground(new java.awt.Color(153, 153, 153));
        Ultimo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sokkyo/icones/ultimo_32x32.png"))); // NOI18N
        Ultimo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Ultimo1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Ultimo1MouseExited(evt);
            }
        });
        Ultimo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ultimo1ActionPerformed(evt);
            }
        });
        getContentPane().add(Ultimo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 500, 40, -1));

        Proximo1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Proximo1.setForeground(new java.awt.Color(153, 153, 153));
        Proximo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sokkyo/icones/proximo_32x32.png"))); // NOI18N
        Proximo1.setToolTipText("Proximo");
        Proximo1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Proximo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Proximo1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Proximo1MouseExited(evt);
            }
        });
        Proximo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Proximo1ActionPerformed(evt);
            }
        });
        getContentPane().add(Proximo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 500, 40, -1));

        Anterior1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Anterior1.setForeground(new java.awt.Color(153, 153, 153));
        Anterior1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sokkyo/icones/anterior_32x32.png"))); // NOI18N
        Anterior1.setToolTipText("Anterior");
        Anterior1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Anterior1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Anterior1MouseExited(evt);
            }
        });
        Anterior1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Anterior1ActionPerformed(evt);
            }
        });
        getContentPane().add(Anterior1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 500, 40, -1));

        Primeiro1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Primeiro1.setForeground(new java.awt.Color(153, 153, 153));
        Primeiro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sokkyo/icones/primeiro_32x32.png"))); // NOI18N
        Primeiro1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Primeiro1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Primeiro1MouseExited(evt);
            }
        });
        Primeiro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Primeiro1ActionPerformed(evt);
            }
        });
        getContentPane().add(Primeiro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, 40, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sokkyo/Icons/LogoNoky.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, 380, 350));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-674)/2, (screenSize.height-586)/2, 674, 586);
    }// </editor-fold>//GEN-END:initComponents

    private void nome11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome11ActionPerformed
       
}//GEN-LAST:event_nome11ActionPerformed

    private void pnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnomeActionPerformed
      
}//GEN-LAST:event_pnomeActionPerformed

    private void cod_pecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cod_pecaActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_cod_pecaActionPerformed

    private void vqtdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_vqtdFocusLost


        nt= Double.parseDouble(vqtd.getText());
        nt1=Double.parseDouble(vvalor.getText());
        nt0 = nt*nt1;
        vtotal.setText(""+nt0);        // TODO add your handling code here:
}//GEN-LAST:event_vqtdFocusLost

    private void BConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BConfirmarActionPerformed

 JOptionPane.showMessageDialog(null,"Venda Efetuada e Cadastrada Com Sucesso!");
        
}//GEN-LAST:event_BConfirmarActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        dispose();
}//GEN-LAST:event_jButton14ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        pnome.setText("");
        cod_peca.setText("");
        vqtd.setText("");
        vtotal.setText("");
        vvalor.setText("");
        nt0 = 0;

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        pnome.setText("");
        cod_peca.setText("");
        vqtd.setText("");
        vtotal.setText("");
        nome11.setText("");
        vendedor.setText("");
        nt0 = 0;
}//GEN-LAST:event_jButton15ActionPerformed

    private void jButton15FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton15FocusLost
        // TODO add your handling code here:
}//GEN-LAST:event_jButton15FocusLost

    private void vspreçoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_vspreçoFocusLost
Double v = Double.parseDouble(vspreço.getText());
  nt0 = v + nt0;
  vspreço1.setText(""+nt0);
    }//GEN-LAST:event_vspreçoFocusLost

    private void Ultimo1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ultimo1MouseEntered

}//GEN-LAST:event_Ultimo1MouseEntered

    private void Ultimo1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ultimo1MouseExited

}//GEN-LAST:event_Ultimo1MouseExited

    private void Ultimo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ultimo1ActionPerformed
      
}//GEN-LAST:event_Ultimo1ActionPerformed

    private void Proximo1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Proximo1MouseEntered

}//GEN-LAST:event_Proximo1MouseEntered

    private void Proximo1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Proximo1MouseExited

}//GEN-LAST:event_Proximo1MouseExited

    private void Proximo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Proximo1ActionPerformed
       
}//GEN-LAST:event_Proximo1ActionPerformed

    private void Anterior1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Anterior1MouseEntered

}//GEN-LAST:event_Anterior1MouseEntered

    private void Anterior1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Anterior1MouseExited

}//GEN-LAST:event_Anterior1MouseExited

    private void Anterior1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Anterior1ActionPerformed
       
}//GEN-LAST:event_Anterior1ActionPerformed

    private void Primeiro1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Primeiro1MouseEntered

}//GEN-LAST:event_Primeiro1MouseEntered

    private void Primeiro1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Primeiro1MouseExited

}//GEN-LAST:event_Primeiro1MouseExited

    private void Primeiro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Primeiro1ActionPerformed
       
}//GEN-LAST:event_Primeiro1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new CadastroOrcamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Anterior1;
    private javax.swing.JButton BConfirmar;
    private javax.swing.JButton Primeiro1;
    private javax.swing.JButton Proximo1;
    private javax.swing.JButton Ultimo1;
    private javax.swing.JTextField cod_peca;
    private javax.swing.JTextField codigOS;
    private javax.swing.JFormattedTextField datae;
    private javax.swing.JTextArea descrição;
    private javax.swing.JComboBox dias;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField modelo;
    private javax.swing.JTextField nome11;
    private javax.swing.JTextField placa;
    private javax.swing.JTextField pnome;
    private javax.swing.JTextField vendedor;
    private javax.swing.JTextField vqtd;
    private javax.swing.JTextField vscodigocli;
    private javax.swing.JTextField vspreço;
    private javax.swing.JTextField vspreço1;
    private javax.swing.JTextField vtotal;
    private javax.swing.JTextField vvalor;
    // End of variables declaration//GEN-END:variables

}
