/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CadastoFuncionario.java
 *
 * Created on 04/09/2010, 13:25:13
 */
package br.com.sokkyo.view.cadastros;

import java.io.File;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author Adm
 */
public final class CadastoFuncionario extends javax.swing.JFrame {

    public int navega = 0; //Variavel para Saber qual botao é o que ta dando problema
    public int n1;
    Date data = new Date();

    /**
     * Creates new form CadastoFuncionario
     */
    public CadastoFuncionario() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        BuscaNome = new javax.swing.JTextField();
        buscaCPF = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        masculino = new javax.swing.JRadioButton();
        feminino = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        fnome = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        fcodigo = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        fendereço = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        fotux = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        Fotu = new javax.swing.JLabel();
        fcep = new javax.swing.JFormattedTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        bairro = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        ddd = new javax.swing.JFormattedTextField();
        jTextField1 = new javax.swing.JFormattedTextField();
        jLabel35 = new javax.swing.JLabel();
        numero = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        frg = new javax.swing.JFormattedTextField();
        jLabel20 = new javax.swing.JLabel();
        fcpf = new javax.swing.JFormattedTextField();
        jLabel26 = new javax.swing.JLabel();
        entrada = new javax.swing.JFormattedTextField();
        jLabel21 = new javax.swing.JLabel();
        fdata = new javax.swing.JFormattedTextField();
        carteira = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        residencia = new javax.swing.JComboBox();
        fsalario = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        uf = new javax.swing.JComboBox();
        jLabel30 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        estadocivil = new javax.swing.JComboBox();
        jButton14 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        numerodecliente = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Primeiro1 = new javax.swing.JButton();
        Anterior2 = new javax.swing.JButton();
        Proximo1 = new javax.swing.JButton();
        Ultimo1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Funcionario");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sokkyo/Icons/7797_32x32.png"))); // NOI18N
        jButton8.setMnemonic('N');
        jButton8.setText(" Novo");
        jButton8.setToolTipText("Novo Cadastro");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jButton8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jButton8FocusLost(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 100, 40));

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sokkyo/icones/gtk_edit.png"))); // NOI18N
        jButton9.setMnemonic('E');
        jButton9.setText(" Editar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 6, 110, 40));

        jButton10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sokkyo/icones/12594410.png"))); // NOI18N
        jButton10.setMnemonic('x');
        jButton10.setText(" Excluir");
        jButton10.setToolTipText("Excluir Cadastro");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 6, 110, 40));

        jButton11.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sokkyo/icones/fechar_32x32.png"))); // NOI18N
        jButton11.setMnemonic('s');
        jButton11.setText(" Sair");
        jButton11.setToolTipText("Sair do Menu Cadastro");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 6, 110, 40));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sokkyo/icones/ok-32x32.png"))); // NOI18N
        jButton2.setText(" Confirmar");
        jButton2.setToolTipText("Confirmar cadastro de Cliente");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, 130, -1));

        jButton13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sokkyo/icones/6155_32x32.png"))); // NOI18N
        jButton13.setMnemonic('c');
        jButton13.setText(" Cancelar");
        jButton13.setToolTipText("Cancelar Cadastro de Cliente");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, 130, 40));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar Funcionario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(153, 153, 153))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel27.setText("CPF:");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 30, 20));

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel28.setText("Nome:");
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 40, 20));

        BuscaNome.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BuscaNome.setToolTipText("Digite o nome do cliente e aperte 'Enter' para efetuar a busca");
        BuscaNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscaNomeActionPerformed(evt);
            }
        });
        jPanel3.add(BuscaNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 200, -1));

        buscaCPF.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buscaCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaCPFActionPerformed(evt);
            }
        });
        jPanel3.add(buscaCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 110, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 430, 50));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sexo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(153, 153, 153))); // NOI18N
        jPanel4.setToolTipText("Escolha o Sexo do cliente");
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(masculino);
        masculino.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        masculino.setText("Masculino");
        masculino.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                masculinoItemStateChanged(evt);
            }
        });
        masculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masculinoActionPerformed(evt);
            }
        });
        jPanel4.add(masculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        buttonGroup1.add(feminino);
        feminino.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        feminino.setText("Feminino");
        feminino.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                femininoItemStateChanged(evt);
            }
        });
        feminino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femininoActionPerformed(evt);
            }
        });
        jPanel4.add(feminino, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 180, 50));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dado do Funcionario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(153, 153, 153))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel16.setText("Nome:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 50, 20));

        fnome.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnomeActionPerformed(evt);
            }
        });
        jPanel1.add(fnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 200, -1));

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel23.setText("Codigo:");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 30, 50, 20));

        fcodigo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fcodigo.setNextFocusableComponent(fendereço);
        fcodigo.setRequestFocusEnabled(false);
        jPanel1.add(fcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 100, -1));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel17.setText("Endereço:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 70, 20));

        fendereço.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fendereço.setToolTipText("Rua 'x' , nº 'xxx' av 'xx' jd.'xxxxxx'");
        fendereço.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fendereçoActionPerformed(evt);
            }
        });
        jPanel1.add(fendereço, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 200, -1));

        jPanel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        fotux.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sokkyo/icones/people(3).png"))); // NOI18N
        fotux.setToolTipText("Foto do Cliente *Opcional");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fotux, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fotux, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 130, 130));

        jButton12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sokkyo/icones/http___iconesbr.oficinadanet.com_10684_32x32.png"))); // NOI18N
        jButton12.setText("Selecionar");
        jButton12.setToolTipText("Selecionar Foto");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 130, 40));

        Fotu.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Fotu.setText("Foto");
        jPanel1.add(Fotu, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 130, 20));

        try {
            fcep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fcep.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel1.add(fcep, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 100, -1));

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel24.setText("CEP:");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 40, 20));

        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel29.setText("Bairro:");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 50, 20));

        bairro.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel1.add(bairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 120, -1));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel22.setText("Tel:");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 40, 20));

        try {
            ddd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(0##)")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ddd.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel1.add(ddd, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 40, -1));

        try {
            jTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####.####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 70, -1));

        jLabel35.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel35.setText("Nº:");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 20, 20));

        numero.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        numero.setToolTipText("Numero da Residencia");
        jPanel1.add(numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 50, -1));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel19.setText("RG:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 40, 20));

        try {
            frg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        frg.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel1.add(frg, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 120, -1));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel20.setText("CPF:");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 40, 20));

        try {
            fcpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fcpf.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel1.add(fcpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 120, 20));

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel26.setText("Entrada:");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 50, 20));

        try {
            entrada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        entrada.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel1.add(entrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 120, -1));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel21.setText("Data Nascimento");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 100, 20));

        try {
            fdata.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fdata.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel1.add(fdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 100, -1));

        carteira.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        carteira.setToolTipText("Numero da Carteira de Trabalho");
        jPanel1.add(carteira, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 100, 20));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("Nº CT:");
        jLabel1.setToolTipText("Numero da Carteira de Trabalho");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 50, 20));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mecanico", "Gerente", "Mecanico Chefe" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 100, 20));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Cargo:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 50, 20));

        jLabel37.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel37.setText("Tipo Residencia:");
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 100, 20));

        residencia.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        residencia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Propria", "Alugada", "Outra..." }));
        residencia.setToolTipText("Tipo de Residencia em que o cliente vive");
        jPanel1.add(residencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 100, -1));

        fsalario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fsalario.setToolTipText("Rua 'x' , nº 'xxx' av 'xx' jd.'xxxxxx'");
        fsalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fsalarioActionPerformed(evt);
            }
        });
        jPanel1.add(fsalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 120, 20));

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel25.setText("Salario:");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 50, 20));

        jLabel50.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel50.setText("Email:");
        jPanel1.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 50, 20));

        email.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        email.setToolTipText("Digite o endereço do cliente ");
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 240, 20));

        uf.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        uf.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SP", "RJ", "MG", "PA", "PB", "PR", "TO", "AM", "BA", "SC" }));
        uf.setToolTipText("Estado ");
        jPanel1.add(uf, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 50, -1));

        jLabel30.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel30.setText("UF:");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 20, 20));

        jLabel42.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel42.setText("Estado Civil:");
        jPanel1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 80, 20));

        estadocivil.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        estadocivil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Solteiro(a)", "Casado(a)", "Viuvo(a)" }));
        estadocivil.setToolTipText("Estado Civil do Cliente");
        jPanel1.add(estadocivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 100, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 610, 270));

        jButton14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton14.setMnemonic('c');
        jButton14.setText("Cadastrar Usuario");
        jButton14.setToolTipText("Cancelar Cadastro de Cliente");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, 130, 40));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel18.setText("  Numero de funcionario Cadastrados:   ");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 20));

        numerodecliente.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        numerodecliente.setText("0");
        jPanel2.add(numerodecliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 30, 20));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Nokys Sistemas");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 100, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 800, -1));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Funcionarios Cadastradados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(153, 153, 153))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Telefone", "CPF", "RG"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 590, 120));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 610, 150));

        Primeiro1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Primeiro1.setForeground(new java.awt.Color(153, 153, 153));
        Primeiro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sokkyo/icones/primeiro_32x32.png"))); // NOI18N
        Primeiro1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Primeiro1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Primeiro1MouseExited(evt);
            }
        });
        Primeiro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Primeiro1ActionPerformed(evt);
            }
        });
        getContentPane().add(Primeiro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 40, -1));

        Anterior2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Anterior2.setForeground(new java.awt.Color(153, 153, 153));
        Anterior2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sokkyo/icones/anterior_32x32.png"))); // NOI18N
        Anterior2.setToolTipText("Anterior");
        Anterior2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Anterior2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Anterior2MouseExited(evt);
            }
        });
        Anterior2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Anterior2ActionPerformed(evt);
            }
        });
        getContentPane().add(Anterior2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 40, -1));

        Proximo1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Proximo1.setForeground(new java.awt.Color(153, 153, 153));
        Proximo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sokkyo/icones/proximo_32x32.png"))); // NOI18N
        Proximo1.setToolTipText("Proximo");
        Proximo1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Proximo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Proximo1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Proximo1MouseExited(evt);
            }
        });
        Proximo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Proximo1ActionPerformed(evt);
            }
        });
        getContentPane().add(Proximo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 40, -1));

        Ultimo1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Ultimo1.setForeground(new java.awt.Color(153, 153, 153));
        Ultimo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sokkyo/icones/ultimo_32x32.png"))); // NOI18N
        Ultimo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Ultimo1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Ultimo1MouseExited(evt);
            }
        });
        Ultimo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ultimo1ActionPerformed(evt);
            }
        });
        getContentPane().add(Ultimo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, 40, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sokkyo/Icons/LogoNoky.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, -10, 380, 350));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-787)/2, (screenSize.height-640)/2, 787, 640);
    }// </editor-fold>//GEN-END:initComponents

    private void fnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnomeActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_fnomeActionPerformed

    private void fendereçoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fendereçoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_fendereçoActionPerformed

    private void fsalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fsalarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fsalarioActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        fnome.setText("");
        fcodigo.setText("");
        fendereço.setText("");
        fcep.setText("");
        frg.setText("");
        fsalario.setText("");
        fdata.setText("");
        jTextField1.setText("");
        carteira.setText("");
        fcpf.setText("");
        entrada.setText("");
        ddd.setText("");
        bairro.setText("");
        numero.setText("");
        carteira.setText("");
        email.setText("");
        fotux.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/people(3).png")));

}//GEN-LAST:event_jButton8ActionPerformed

    private void jButton8FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton8FocusLost
}//GEN-LAST:event_jButton8FocusLost

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
}//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
}//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        dispose();
}//GEN-LAST:event_jButton11ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
}//GEN-LAST:event_jButton2ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        fnome.setText("");
        fcodigo.setText("");
        fendereço.setText("");
        fcep.setText("");
        frg.setText("");
        fsalario.setText("");
        fdata.setText("");
        jTextField1.setText("");
        carteira.setText("");
        fcpf.setText("");
        ddd.setText("");
}//GEN-LAST:event_jButton13ActionPerformed

    private void Ultimo1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ultimo1MouseEntered
}//GEN-LAST:event_Ultimo1MouseEntered

    private void Ultimo1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ultimo1MouseExited
}//GEN-LAST:event_Ultimo1MouseExited

    private void Ultimo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ultimo1ActionPerformed
}//GEN-LAST:event_Ultimo1ActionPerformed

    private void Proximo1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Proximo1MouseEntered
}//GEN-LAST:event_Proximo1MouseEntered

    private void Proximo1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Proximo1MouseExited
}//GEN-LAST:event_Proximo1MouseExited

    private void Proximo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Proximo1ActionPerformed
}//GEN-LAST:event_Proximo1ActionPerformed

    private void Anterior2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Anterior2MouseEntered
}//GEN-LAST:event_Anterior2MouseEntered

    private void Anterior2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Anterior2MouseExited
}//GEN-LAST:event_Anterior2MouseExited

    private void Anterior2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Anterior2ActionPerformed
}//GEN-LAST:event_Anterior2ActionPerformed

    private void Primeiro1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Primeiro1MouseEntered
}//GEN-LAST:event_Primeiro1MouseEntered

    private void Primeiro1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Primeiro1MouseExited
}//GEN-LAST:event_Primeiro1MouseExited

    private void Primeiro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Primeiro1ActionPerformed
}//GEN-LAST:event_Primeiro1ActionPerformed

    private void BuscaNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscaNomeActionPerformed
}//GEN-LAST:event_BuscaNomeActionPerformed

    private void buscaCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaCPFActionPerformed
}//GEN-LAST:event_buscaCPFActionPerformed

    private void masculinoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_masculinoItemStateChanged
}//GEN-LAST:event_masculinoItemStateChanged

    private void femininoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_femininoItemStateChanged
}//GEN-LAST:event_femininoItemStateChanged

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        try {
            JFileChooser buscar_foto = new JFileChooser();
            buscar_foto.setCurrentDirectory(new File(""));
            buscar_foto.setDialogTitle("Carregar foto do cliente");
            buscar_foto.showOpenDialog(this);
            String foto = "";
            foto = "" + buscar_foto.getSelectedFile();
            foto = foto.replaceAll("\\\\", "/");
            Fotu.setText(foto);
            fotux.setIcon(new ImageIcon("" + Fotu.getText()));


        } catch (Exception erro) {
        }
}//GEN-LAST:event_jButton12ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
    }//GEN-LAST:event_jButton14ActionPerformed

    private void femininoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femininoActionPerformed
        
    }//GEN-LAST:event_femininoActionPerformed

    private void masculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masculinoActionPerformed

    }//GEN-LAST:event_masculinoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new CadastoFuncionario().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Anterior2;
    private javax.swing.JTextField BuscaNome;
    private javax.swing.JLabel Fotu;
    private javax.swing.JButton Primeiro1;
    private javax.swing.JButton Proximo1;
    private javax.swing.JButton Ultimo1;
    private javax.swing.JTextField bairro;
    private javax.swing.JFormattedTextField buscaCPF;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField carteira;
    private javax.swing.JFormattedTextField ddd;
    private javax.swing.JTextField email;
    private javax.swing.JFormattedTextField entrada;
    private javax.swing.JComboBox estadocivil;
    private javax.swing.JFormattedTextField fcep;
    private javax.swing.JTextField fcodigo;
    private javax.swing.JFormattedTextField fcpf;
    private javax.swing.JFormattedTextField fdata;
    private javax.swing.JRadioButton feminino;
    private javax.swing.JTextField fendereço;
    private javax.swing.JTextField fnome;
    private javax.swing.JLabel fotux;
    private javax.swing.JFormattedTextField frg;
    private javax.swing.JTextField fsalario;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JFormattedTextField jTextField1;
    private javax.swing.JRadioButton masculino;
    private javax.swing.JTextField numero;
    private javax.swing.JLabel numerodecliente;
    private javax.swing.JComboBox residencia;
    private javax.swing.JComboBox uf;
    // End of variables declaration//GEN-END:variables
}
